// Auto-generated tests for asset_processor
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const asset_processorModule = require("../tools/asset_processor");

test("post_apa_reports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = asset_processorModule.handlers.post_apa_reports;
  assert.ok(handler, "Handler post_apa_reports should be defined");

  const result = await handler(mockClient, {"asset_processor_id": "test_asset_processor_id", "assetId": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/lti/asset_processors/test_asset_processor_id/reports");
  assert.deepStrictEqual(calledConfig.data, {"assetId": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_apec_deployment calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = asset_processorModule.handlers.put_apec_deployment;
  assert.ok(handler, "Handler put_apec_deployment should be defined");

  const result = await handler(mockClient, {"context_external_tool_id": "test_context_external_tool_id", "eulaRequired": true});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/lti/asset_processor_eulas/test_context_external_tool_id/deployment");
  assert.deepStrictEqual(calledConfig.data, {"eulaRequired": true});
  assert.deepStrictEqual(result, { success: true });
});

test("post_apec_user calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = asset_processorModule.handlers.post_apec_user;
  assert.ok(handler, "Handler post_apec_user should be defined");

  const result = await handler(mockClient, {"context_external_tool_id": "test_context_external_tool_id", "userId": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/lti/asset_processor_eulas/test_context_external_tool_id/user");
  assert.deepStrictEqual(calledConfig.data, {"userId": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_apec_user calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = asset_processorModule.handlers.delete_apec_user;
  assert.ok(handler, "Handler delete_apec_user should be defined");

  const result = await handler(mockClient, {"context_external_tool_id": "test_context_external_tool_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/lti/asset_processor_eulas/test_context_external_tool_id/user");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
