// Auto-generated tests for assignments
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const assignmentsModule = require("../tools/assignments");

test("delete_cc_assignments_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.delete_cc_assignments_id;
  assert.ok(handler, "Handler delete_cc_assignments_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_assignments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_cc_assignments;
  assert.ok(handler, "Handler get_cc_assignments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaga_assignments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_ccaga_assignments;
  assert.ok(handler, "Handler get_ccaga_assignments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_group_id": "test_assignment_group_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignment_groups/test_assignment_group_id/assignments");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uucc_assignments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_uucc_assignments;
  assert.ok(handler, "Handler get_uucc_assignments should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/courses/test_course_id/assignments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccaa_duplicate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.post_ccaa_duplicate;
  assert.ok(handler, "Handler post_ccaa_duplicate should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "result_type": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/duplicate");
  assert.deepStrictEqual(calledConfig.data, {"result_type": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaauu_group_members calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_ccaauu_group_members;
  assert.ok(handler, "Handler get_ccaauu_group_members should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/users/test_user_id/group_members");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_assignments_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_cc_assignments_id;
  assert.ok(handler, "Handler get_cc_assignments_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_assignments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.post_cc_assignments;
  assert.ok(handler, "Handler post_cc_assignments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_name": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments");
  assert.deepStrictEqual(calledConfig.data, {"assignment[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_assignments_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.put_cc_assignments_id;
  assert.ok(handler, "Handler put_cc_assignments_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "assignment_name": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_id");
  assert.deepStrictEqual(calledConfig.data, {"assignment[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cca_bulk_update calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.put_cca_bulk_update;
  assert.ok(handler, "Handler put_cca_bulk_update should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/bulk_update");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_ccaa_overrides;
  assert.ok(handler, "Handler get_ccaa_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/overrides");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_overrides_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_ccaa_overrides_id;
  assert.ok(handler, "Handler get_ccaa_overrides_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/overrides/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggaa_override calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_ggaa_override;
  assert.ok(handler, "Handler get_ggaa_override should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/assignments/test_assignment_id/override");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_scaa_override calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_scaa_override;
  assert.ok(handler, "Handler get_scaa_override should be defined");

  const result = await handler(mockClient, {"course_section_id": "test_course_section_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_course_section_id/assignments/test_assignment_id/override");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccaa_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.post_ccaa_overrides;
  assert.ok(handler, "Handler post_ccaa_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "assignment_override_student_ids": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/overrides");
  assert.deepStrictEqual(calledConfig.data, {"assignment_override[student_ids][]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaa_overrides_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.put_ccaa_overrides_id;
  assert.ok(handler, "Handler put_ccaa_overrides_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "id": "test_id", "assignment_override_student_ids": 123});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/overrides/test_id");
  assert.deepStrictEqual(calledConfig.data, {"assignment_override[student_ids][]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccaa_overrides_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.delete_ccaa_overrides_id;
  assert.ok(handler, "Handler delete_ccaa_overrides_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/overrides/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cca_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.get_cca_overrides;
  assert.ok(handler, "Handler get_cca_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_overrides_id": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/overrides");
  assert.deepStrictEqual(calledConfig.params, {"assignment_overrides[][id]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cca_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.post_cca_overrides;
  assert.ok(handler, "Handler post_cca_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_overrides": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/overrides");
  assert.deepStrictEqual(calledConfig.data, {"assignment_overrides[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cca_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = assignmentsModule.handlers.put_cca_overrides;
  assert.ok(handler, "Handler put_cca_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_overrides": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/overrides");
  assert.deepStrictEqual(calledConfig.data, {"assignment_overrides[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
