// Auto-generated tests for authentication_providers
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const authentication_providersModule = require("../tools/authentication_providers");

test("get_aa_authentication_providers calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.get_aa_authentication_providers;
  assert.ok(handler, "Handler get_aa_authentication_providers should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_authentication_providers_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.get_aa_authentication_providers_id;
  assert.ok(handler, "Handler get_aa_authentication_providers_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_authentication_providers calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.post_aa_authentication_providers;
  assert.ok(handler, "Handler post_aa_authentication_providers should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_authentication_providers_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.put_aa_authentication_providers_id;
  assert.ok(handler, "Handler put_aa_authentication_providers_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers/test_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aa_authentication_providers_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.delete_aa_authentication_providers_id;
  assert.ok(handler, "Handler delete_aa_authentication_providers_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aaapi_restore calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.put_aaapi_restore;
  assert.ok(handler, "Handler put_aaapi_restore should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers/test_id/restore");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_sso_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.get_aa_sso_settings;
  assert.ok(handler, "Handler get_aa_sso_settings should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/sso_settings");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_sso_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.put_aa_sso_settings;
  assert.ok(handler, "Handler put_aa_sso_settings should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/sso_settings");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aaap_force_password_reset calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = authentication_providersModule.handlers.post_aaap_force_password_reset;
  assert.ok(handler, "Handler post_aaap_force_password_reset should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/authentication_providers/force_password_reset");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});
