const test = require("node:test");
const assert = require("node:assert");
const autoGenerated = require("../tools/auto_generated");

test("auto_generated GET tool with path parameters", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return {
      data: [{ id: 99, token_hint: "hint" }]
    };
  };

  // Test auto_get_users_user_id_user_generated_tokens
  // GET /api/v1/users/:user_id/user_generated_tokens
  const handler = autoGenerated.handlers.auto_get_users_user_id_user_generated_tokens;
  
  // Verify handler exists
  assert.ok(handler, "Handler auto_get_users_user_id_user_generated_tokens should be defined");

  const result = await handler(mockClient, {
    user_id: 12345,
    per_page: 50
  });

  assert.deepStrictEqual(calledConfig, {
    method: "get",
    url: "/api/v1/users/12345/user_generated_tokens",
    params: {
      per_page: 50
    }
  });

  assert.deepStrictEqual(result, [{ id: 99, token_hint: "hint" }]);
});

test("auto_generated POST tool with path and body parameters", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return {
      data: { status: "created" }
    };
  };

  // Test auto_post_users_user_id_educator_accessibility_course_scan
  // POST /api/v1/users/:user_id/educator_accessibility_course_scan
  const handler = autoGenerated.handlers.auto_post_users_user_id_educator_accessibility_course_scan;
  assert.ok(handler, "Handler auto_post_users_user_id_educator_accessibility_course_scan should be defined");

  const result = await handler(mockClient, {
    user_id: "me",
    scan_option: "full"
  });

  assert.deepStrictEqual(calledConfig, {
    method: "post",
    url: "/api/v1/users/me/educator_accessibility_course_scan",
    data: {
      scan_option: "full"
    }
  });

  assert.deepStrictEqual(result, { status: "created" });
});

test("auto_generated throws error on missing required path parameters", async () => {
  const mockClient = async (config) => {
    return { data: {} };
  };

  const handler = autoGenerated.handlers.auto_get_users_user_id_user_generated_tokens;
  
  await assert.rejects(
    async () => {
      await handler(mockClient, {
        per_page: 10
      });
    },
    /Missing required path parameter: user_id/
  );
});
