// Auto-generated tests for blackout_dates
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const blackout_datesModule = require("../tools/blackout_dates");

test("get_cc_blackout_dates calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.get_cc_blackout_dates;
  assert.ok(handler, "Handler get_cc_blackout_dates should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_blackout_dates calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.get_aa_blackout_dates;
  assert.ok(handler, "Handler get_aa_blackout_dates should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/blackout_dates");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_blackout_dates_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.get_cc_blackout_dates_id;
  assert.ok(handler, "Handler get_cc_blackout_dates_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_blackout_dates_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.get_aa_blackout_dates_id;
  assert.ok(handler, "Handler get_aa_blackout_dates_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/blackout_dates/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccbd_new calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.get_ccbd_new;
  assert.ok(handler, "Handler get_ccbd_new should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates/new");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aabd_new calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.get_aabd_new;
  assert.ok(handler, "Handler get_aabd_new should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/blackout_dates/new");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_blackout_dates calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.post_cc_blackout_dates;
  assert.ok(handler, "Handler post_cc_blackout_dates should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_blackout_dates calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.post_aa_blackout_dates;
  assert.ok(handler, "Handler post_aa_blackout_dates should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "start_date": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/blackout_dates");
  assert.deepStrictEqual(calledConfig.data, {"start_date": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_blackout_dates_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.put_cc_blackout_dates_id;
  assert.ok(handler, "Handler put_cc_blackout_dates_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates/test_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_blackout_dates_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.put_aa_blackout_dates_id;
  assert.ok(handler, "Handler put_aa_blackout_dates_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "start_date": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/blackout_dates/test_id");
  assert.deepStrictEqual(calledConfig.data, {"start_date": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_cc_blackout_dates_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.delete_cc_blackout_dates_id;
  assert.ok(handler, "Handler delete_cc_blackout_dates_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aa_blackout_dates_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.delete_aa_blackout_dates_id;
  assert.ok(handler, "Handler delete_aa_blackout_dates_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/blackout_dates/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_blackout_dates calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = blackout_datesModule.handlers.put_cc_blackout_dates;
  assert.ok(handler, "Handler put_cc_blackout_dates should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "blackout_dates": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/blackout_dates");
  assert.deepStrictEqual(calledConfig.data, {"blackout_dates:": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
