// Auto-generated tests for communication_channels
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const communication_channelsModule = require("../tools/communication_channels");

test("get_uu_communication_channels calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = communication_channelsModule.handlers.get_uu_communication_channels;
  assert.ok(handler, "Handler get_uu_communication_channels should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_uu_communication_channels calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = communication_channelsModule.handlers.post_uu_communication_channels;
  assert.ok(handler, "Handler post_uu_communication_channels should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "communication_channel_address": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels");
  assert.deepStrictEqual(calledConfig.data, {"communication_channel[address]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_uu_communication_channels_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = communication_channelsModule.handlers.delete_uu_communication_channels_id;
  assert.ok(handler, "Handler delete_uu_communication_channels_id should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_uu_communication_channels_type_address calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = communication_channelsModule.handlers.delete_uu_communication_channels_type_address;
  assert.ok(handler, "Handler delete_uu_communication_channels_type_address should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "type": "test_type", "address": "test_address"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/communication_channels/test_type/test_address");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_uscc_push calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = communication_channelsModule.handlers.delete_uscc_push;
  assert.ok(handler, "Handler delete_uscc_push should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/communication_channels/push");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
