// Auto-generated tests for content_exports
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const content_exportsModule = require("../tools/content_exports");

test("get_cc_content_exports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.get_cc_content_exports;
  assert.ok(handler, "Handler get_cc_content_exports should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/content_exports");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_content_exports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.get_gg_content_exports;
  assert.ok(handler, "Handler get_gg_content_exports should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/content_exports");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_content_exports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.get_uu_content_exports;
  assert.ok(handler, "Handler get_uu_content_exports should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/content_exports");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_content_exports_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.get_cc_content_exports_id;
  assert.ok(handler, "Handler get_cc_content_exports_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/content_exports/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_content_exports_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.get_gg_content_exports_id;
  assert.ok(handler, "Handler get_gg_content_exports_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/content_exports/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_content_exports_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.get_uu_content_exports_id;
  assert.ok(handler, "Handler get_uu_content_exports_id should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/content_exports/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_content_exports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.post_cc_content_exports;
  assert.ok(handler, "Handler post_cc_content_exports should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/content_exports");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_gg_content_exports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.post_gg_content_exports;
  assert.ok(handler, "Handler post_gg_content_exports should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/content_exports");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_uu_content_exports calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_exportsModule.handlers.post_uu_content_exports;
  assert.ok(handler, "Handler post_uu_content_exports should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "export_type": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/content_exports");
  assert.deepStrictEqual(calledConfig.data, {"export_type": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
