// Auto-generated tests for content_security_policy_settings
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const content_security_policy_settingsModule = require("../tools/content_security_policy_settings");

test("get_cc_csp_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.get_cc_csp_settings;
  assert.ok(handler, "Handler get_cc_csp_settings should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/csp_settings");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_csp_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.get_aa_csp_settings;
  assert.ok(handler, "Handler get_aa_csp_settings should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/csp_settings");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_csp_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.put_cc_csp_settings;
  assert.ok(handler, "Handler put_cc_csp_settings should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/csp_settings");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_csp_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.put_aa_csp_settings;
  assert.ok(handler, "Handler put_aa_csp_settings should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "status": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/csp_settings");
  assert.deepStrictEqual(calledConfig.data, {"status": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aacs_lock calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.put_aacs_lock;
  assert.ok(handler, "Handler put_aacs_lock should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "settings_locked": true});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/csp_settings/lock");
  assert.deepStrictEqual(calledConfig.data, {"settings_locked": true});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aacs_domains calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.post_aacs_domains;
  assert.ok(handler, "Handler post_aacs_domains should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "domain": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/csp_settings/domains");
  assert.deepStrictEqual(calledConfig.data, {"domain": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aacsd_batch_create calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.post_aacsd_batch_create;
  assert.ok(handler, "Handler post_aacsd_batch_create should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "domains": ["test_val"]});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/csp_settings/domains/batch_create");
  assert.deepStrictEqual(calledConfig.data, {"domains": ["test_val"]});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aacs_domains calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = content_security_policy_settingsModule.handlers.delete_aacs_domains;
  assert.ok(handler, "Handler delete_aacs_domains should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "domain": "test_val"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/csp_settings/domains");
  assert.deepStrictEqual(calledConfig.params, {"domain": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
