// Auto-generated tests for discussion_topics
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const discussion_topicsModule = require("../tools/discussion_topics");

test("get_cc_discussion_topics calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_cc_discussion_topics;
  assert.ok(handler, "Handler get_cc_discussion_topics should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_discussion_topics calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_gg_discussion_topics;
  assert.ok(handler, "Handler get_gg_discussion_topics should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_discussion_topics calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_cc_discussion_topics;
  assert.ok(handler, "Handler post_cc_discussion_topics should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_gg_discussion_topics calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_gg_discussion_topics;
  assert.ok(handler, "Handler post_gg_discussion_topics should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "title": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics");
  assert.deepStrictEqual(calledConfig.data, {"title": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_discussion_topics_topic_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_cc_discussion_topics_topic_id;
  assert.ok(handler, "Handler put_cc_discussion_topics_topic_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_gg_discussion_topics_topic_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_gg_discussion_topics_topic_id;
  assert.ok(handler, "Handler put_gg_discussion_topics_topic_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "title": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id");
  assert.deepStrictEqual(calledConfig.data, {"title": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_cc_discussion_topics_topic_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_cc_discussion_topics_topic_id;
  assert.ok(handler, "Handler delete_cc_discussion_topics_topic_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_gg_discussion_topics_topic_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_gg_discussion_topics_topic_id;
  assert.ok(handler, "Handler delete_gg_discussion_topics_topic_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdt_reorder calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdt_reorder;
  assert.ok(handler, "Handler post_ccdt_reorder should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/reorder");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdt_reorder calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdt_reorder;
  assert.ok(handler, "Handler post_ggdt_reorder should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "order": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/reorder");
  assert.deepStrictEqual(calledConfig.data, {"order[]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdtt_entries_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdtt_entries_id;
  assert.ok(handler, "Handler put_ccdtt_entries_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdtt_entries_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdtt_entries_id;
  assert.ok(handler, "Handler put_ggdtt_entries_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "id": "test_id", "message": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_id");
  assert.deepStrictEqual(calledConfig.data, {"message": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccdtt_entries_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ccdtt_entries_id;
  assert.ok(handler, "Handler delete_ccdtt_entries_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ggdtt_entries_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ggdtt_entries_id;
  assert.ok(handler, "Handler delete_ggdtt_entries_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_discussion_topics_topic_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_cc_discussion_topics_topic_id;
  assert.ok(handler, "Handler get_cc_discussion_topics_topic_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_discussion_topics_topic_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_gg_discussion_topics_topic_id;
  assert.ok(handler, "Handler get_gg_discussion_topics_topic_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccdtt_summaries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ccdtt_summaries;
  assert.ok(handler, "Handler get_ccdtt_summaries should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/summaries");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggdtt_summaries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ggdtt_summaries;
  assert.ok(handler, "Handler get_ggdtt_summaries should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/summaries");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdtt_summaries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdtt_summaries;
  assert.ok(handler, "Handler post_ccdtt_summaries should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/summaries");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdtt_summaries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdtt_summaries;
  assert.ok(handler, "Handler post_ggdtt_summaries should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "userInput": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/summaries");
  assert.deepStrictEqual(calledConfig.data, {"userInput": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdtts_disable calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdtts_disable;
  assert.ok(handler, "Handler put_ccdtts_disable should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/summaries/disable");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdtts_disable calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdtts_disable;
  assert.ok(handler, "Handler put_ggdtts_disable should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/summaries/disable");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdttss_feedback calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdttss_feedback;
  assert.ok(handler, "Handler post_ccdttss_feedback should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "summary_id": "test_summary_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/summaries/test_summary_id/feedback");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdttss_feedback calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdttss_feedback;
  assert.ok(handler, "Handler post_ggdttss_feedback should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "summary_id": "test_summary_id", "action": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/summaries/test_summary_id/feedback");
  assert.deepStrictEqual(calledConfig.data, {"_action": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccdtt_view calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ccdtt_view;
  assert.ok(handler, "Handler get_ccdtt_view should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/view");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggdtt_view calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ggdtt_view;
  assert.ok(handler, "Handler get_ggdtt_view should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/view");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdtt_entries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdtt_entries;
  assert.ok(handler, "Handler post_ccdtt_entries should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdtt_entries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdtt_entries;
  assert.ok(handler, "Handler post_ggdtt_entries should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "message": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries");
  assert.deepStrictEqual(calledConfig.data, {"message": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdtt_duplicate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdtt_duplicate;
  assert.ok(handler, "Handler post_ccdtt_duplicate should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/duplicate");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdtt_duplicate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdtt_duplicate;
  assert.ok(handler, "Handler post_ggdtt_duplicate should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/duplicate");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccdtt_entries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ccdtt_entries;
  assert.ok(handler, "Handler get_ccdtt_entries should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggdtt_entries calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ggdtt_entries;
  assert.ok(handler, "Handler get_ggdtt_entries should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdttee_replies calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdttee_replies;
  assert.ok(handler, "Handler post_ccdttee_replies should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_entry_id/replies");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdttee_replies calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdttee_replies;
  assert.ok(handler, "Handler post_ggdttee_replies should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id", "message": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_entry_id/replies");
  assert.deepStrictEqual(calledConfig.data, {"message": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccdttee_replies calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ccdttee_replies;
  assert.ok(handler, "Handler get_ccdttee_replies should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_entry_id/replies");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggdttee_replies calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ggdttee_replies;
  assert.ok(handler, "Handler get_ggdttee_replies should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_entry_id/replies");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccdtt_entry_list calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ccdtt_entry_list;
  assert.ok(handler, "Handler get_ccdtt_entry_list should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entry_list");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggdtt_entry_list calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.get_ggdtt_entry_list;
  assert.ok(handler, "Handler get_ggdtt_entry_list should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "ids": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entry_list");
  assert.deepStrictEqual(calledConfig.params, {"ids[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdtt_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdtt_read;
  assert.ok(handler, "Handler put_ccdtt_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdtt_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdtt_read;
  assert.ok(handler, "Handler put_ggdtt_read should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdt_read_all calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdt_read_all;
  assert.ok(handler, "Handler put_ccdt_read_all should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/read_all");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdt_read_all calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdt_read_all;
  assert.ok(handler, "Handler put_ggdt_read_all should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/read_all");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccdtt_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ccdtt_read;
  assert.ok(handler, "Handler delete_ccdtt_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ggdtt_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ggdtt_read;
  assert.ok(handler, "Handler delete_ggdtt_read should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdtt_read_all calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdtt_read_all;
  assert.ok(handler, "Handler put_ccdtt_read_all should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/read_all");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdtt_read_all calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdtt_read_all;
  assert.ok(handler, "Handler put_ggdtt_read_all should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "forced_read_state": true});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/read_all");
  assert.deepStrictEqual(calledConfig.data, {"forced_read_state": true});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccdtt_read_all calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ccdtt_read_all;
  assert.ok(handler, "Handler delete_ccdtt_read_all should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/read_all");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ggdtt_read_all calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ggdtt_read_all;
  assert.ok(handler, "Handler delete_ggdtt_read_all should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "forced_read_state": true});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/read_all");
  assert.deepStrictEqual(calledConfig.params, {"forced_read_state": true});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdttee_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdttee_read;
  assert.ok(handler, "Handler put_ccdttee_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_entry_id/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdttee_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdttee_read;
  assert.ok(handler, "Handler put_ggdttee_read should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id", "forced_read_state": true});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_entry_id/read");
  assert.deepStrictEqual(calledConfig.data, {"forced_read_state": true});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccdttee_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ccdttee_read;
  assert.ok(handler, "Handler delete_ccdttee_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_entry_id/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ggdttee_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ggdttee_read;
  assert.ok(handler, "Handler delete_ggdttee_read should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id", "forced_read_state": true});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_entry_id/read");
  assert.deepStrictEqual(calledConfig.params, {"forced_read_state": true});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccdttee_rating calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ccdttee_rating;
  assert.ok(handler, "Handler post_ccdttee_rating should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/entries/test_entry_id/rating");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggdttee_rating calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.post_ggdttee_rating;
  assert.ok(handler, "Handler post_ggdttee_rating should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id", "entry_id": "test_entry_id", "rating": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/entries/test_entry_id/rating");
  assert.deepStrictEqual(calledConfig.data, {"rating": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdtt_subscribed calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ccdtt_subscribed;
  assert.ok(handler, "Handler put_ccdtt_subscribed should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/subscribed");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ggdtt_subscribed calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.put_ggdtt_subscribed;
  assert.ok(handler, "Handler put_ggdtt_subscribed should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/subscribed");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccdtt_subscribed calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ccdtt_subscribed;
  assert.ok(handler, "Handler delete_ccdtt_subscribed should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_topic_id/subscribed");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ggdtt_subscribed calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = discussion_topicsModule.handlers.delete_ggdtt_subscribed;
  assert.ok(handler, "Handler delete_ggdtt_subscribed should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "topic_id": "test_topic_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/discussion_topics/test_topic_id/subscribed");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
