// Auto-generated tests for e_portfolios
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const e_portfoliosModule = require("../tools/e_portfolios");

test("get_uu_eportfolios calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.get_uu_eportfolios;
  assert.ok(handler, "Handler get_uu_eportfolios should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/eportfolios");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_eportfolios_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.get_eportfolios_id;
  assert.ok(handler, "Handler get_eportfolios_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/eportfolios/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_eportfolios_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.delete_eportfolios_id;
  assert.ok(handler, "Handler delete_eportfolios_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/eportfolios/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ee_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.get_ee_pages;
  assert.ok(handler, "Handler get_ee_pages should be defined");

  const result = await handler(mockClient, {"eportfolio_id": "test_eportfolio_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/eportfolios/test_eportfolio_id/pages");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ee_moderate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.put_ee_moderate;
  assert.ok(handler, "Handler put_ee_moderate should be defined");

  const result = await handler(mockClient, {"eportfolio_id": "test_eportfolio_id", "spam_status": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/eportfolios/test_eportfolio_id/moderate");
  assert.deepStrictEqual(calledConfig.data, {"spam_status": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_uu_eportfolios calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.put_uu_eportfolios;
  assert.ok(handler, "Handler put_uu_eportfolios should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "spam_status": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/eportfolios");
  assert.deepStrictEqual(calledConfig.data, {"spam_status": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ee_restore calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = e_portfoliosModule.handlers.put_ee_restore;
  assert.ok(handler, "Handler put_ee_restore should be defined");

  const result = await handler(mockClient, {"eportfolio_id": "test_eportfolio_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/eportfolios/test_eportfolio_id/restore");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});
