// Auto-generated tests for enrollments
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const enrollmentsModule = require("../tools/enrollments");

test("get_cc_enrollments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.get_cc_enrollments;
  assert.ok(handler, "Handler get_cc_enrollments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/enrollments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ss_enrollments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.get_ss_enrollments;
  assert.ok(handler, "Handler get_ss_enrollments should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/enrollments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_enrollments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.get_uu_enrollments;
  assert.ok(handler, "Handler get_uu_enrollments should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "type[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/enrollments");
  assert.deepStrictEqual(calledConfig.params, {"type[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_enrollments_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.get_aa_enrollments_id;
  assert.ok(handler, "Handler get_aa_enrollments_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/enrollments/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_enrollments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.post_cc_enrollments;
  assert.ok(handler, "Handler post_cc_enrollments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/enrollments");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ss_enrollments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.post_ss_enrollments;
  assert.ok(handler, "Handler post_ss_enrollments should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "enrollment[start_at]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/enrollments");
  assert.deepStrictEqual(calledConfig.data, {"enrollment[start_at]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_bulk_enrollment calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.post_aa_bulk_enrollment;
  assert.ok(handler, "Handler post_aa_bulk_enrollment should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "user_ids[]": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/bulk_enrollment");
  assert.deepStrictEqual(calledConfig.data, {"user_ids[]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_cc_enrollments_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.delete_cc_enrollments_id;
  assert.ok(handler, "Handler delete_cc_enrollments_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "task": "test_val"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/enrollments/test_id");
  assert.deepStrictEqual(calledConfig.params, {"task": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccei_accept calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.post_ccei_accept;
  assert.ok(handler, "Handler post_ccei_accept should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/enrollments/test_id/accept");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccei_reject calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.post_ccei_reject;
  assert.ok(handler, "Handler post_ccei_reject should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/enrollments/test_id/reject");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccei_reactivate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.put_ccei_reactivate;
  assert.ok(handler, "Handler put_ccei_reactivate should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/enrollments/test_id/reactivate");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccuu_last_attended calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.put_ccuu_last_attended;
  assert.ok(handler, "Handler put_ccuu_last_attended should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "user_id": "test_user_id", "date": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/users/test_user_id/last_attended");
  assert.deepStrictEqual(calledConfig.data, {"date": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_temporary_enrollment_status calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.get_uu_temporary_enrollment_status;
  assert.ok(handler, "Handler get_uu_temporary_enrollment_status should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "account_id": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/temporary_enrollment_status");
  assert.deepStrictEqual(calledConfig.params, {"account_id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_temporary_enrollment_status calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollmentsModule.handlers.get_temporary_enrollment_status;
  assert.ok(handler, "Handler get_temporary_enrollment_status should be defined");

  const result = await handler(mockClient, {"user_ids[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/temporary_enrollment_status");
  assert.deepStrictEqual(calledConfig.params, {"user_ids[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
