// Auto-generated tests for enrollment_terms
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const enrollment_termsModule = require("../tools/enrollment_terms");

test("post_aa_terms calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollment_termsModule.handlers.post_aa_terms;
  assert.ok(handler, "Handler post_aa_terms should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "enrollment_term[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/terms");
  assert.deepStrictEqual(calledConfig.data, {"enrollment_term[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_terms_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollment_termsModule.handlers.put_aa_terms_id;
  assert.ok(handler, "Handler put_aa_terms_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "enrollment_term[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/terms/test_id");
  assert.deepStrictEqual(calledConfig.data, {"enrollment_term[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aa_terms_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollment_termsModule.handlers.delete_aa_terms_id;
  assert.ok(handler, "Handler delete_aa_terms_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/terms/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_terms calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollment_termsModule.handlers.get_aa_terms;
  assert.ok(handler, "Handler get_aa_terms should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "workflow_state[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/terms");
  assert.deepStrictEqual(calledConfig.params, {"workflow_state[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_terms_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = enrollment_termsModule.handlers.get_aa_terms_id;
  assert.ok(handler, "Handler get_aa_terms_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/terms/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
