// Auto-generated tests for external_tools
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const external_toolsModule = require("../tools/external_tools");

test("get_cc_external_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_cc_external_tools;
  assert.ok(handler, "Handler get_cc_external_tools should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_external_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_aa_external_tools;
  assert.ok(handler, "Handler get_aa_external_tools should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_external_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_gg_external_tools;
  assert.ok(handler, "Handler get_gg_external_tools should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "search_term": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/external_tools");
  assert.deepStrictEqual(calledConfig.params, {"search_term": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccet_sessionless_launch calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_ccet_sessionless_launch;
  assert.ok(handler, "Handler get_ccet_sessionless_launch should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools/sessionless_launch");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aaet_sessionless_launch calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_aaet_sessionless_launch;
  assert.ok(handler, "Handler get_aaet_sessionless_launch should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/sessionless_launch");
  assert.deepStrictEqual(calledConfig.params, {"id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_external_tools_external_tool_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_cc_external_tools_external_tool_id;
  assert.ok(handler, "Handler get_cc_external_tools_external_tool_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "external_tool_id": "test_external_tool_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools/test_external_tool_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_external_tools_external_tool_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_aa_external_tools_external_tool_id;
  assert.ok(handler, "Handler get_aa_external_tools_external_tool_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "external_tool_id": "test_external_tool_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/test_external_tool_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_external_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.post_cc_external_tools;
  assert.ok(handler, "Handler post_cc_external_tools should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_external_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.post_aa_external_tools;
  assert.ok(handler, "Handler post_aa_external_tools should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "client_id": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools");
  assert.deepStrictEqual(calledConfig.data, {"client_id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_external_tools_external_tool_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.put_cc_external_tools_external_tool_id;
  assert.ok(handler, "Handler put_cc_external_tools_external_tool_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "external_tool_id": "test_external_tool_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools/test_external_tool_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_external_tools_external_tool_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.put_aa_external_tools_external_tool_id;
  assert.ok(handler, "Handler put_aa_external_tools_external_tool_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "external_tool_id": "test_external_tool_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/test_external_tool_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_cc_external_tools_external_tool_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.delete_cc_external_tools_external_tool_id;
  assert.ok(handler, "Handler delete_cc_external_tools_external_tool_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "external_tool_id": "test_external_tool_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools/test_external_tool_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aa_external_tools_external_tool_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.delete_aa_external_tools_external_tool_id;
  assert.ok(handler, "Handler delete_aa_external_tools_external_tool_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "external_tool_id": "test_external_tool_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/test_external_tool_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aaet_rce_favorites_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.post_aaet_rce_favorites_id;
  assert.ok(handler, "Handler post_aaet_rce_favorites_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/rce_favorites/test_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aaet_rce_favorites_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.delete_aaet_rce_favorites_id;
  assert.ok(handler, "Handler delete_aaet_rce_favorites_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/rce_favorites/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aaet_top_nav_favorites_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.post_aaet_top_nav_favorites_id;
  assert.ok(handler, "Handler post_aaet_top_nav_favorites_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/top_nav_favorites/test_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aaet_top_nav_favorites_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.delete_aaet_top_nav_favorites_id;
  assert.ok(handler, "Handler delete_aaet_top_nav_favorites_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/external_tools/top_nav_favorites/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_et_visible_course_nav_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_et_visible_course_nav_tools;
  assert.ok(handler, "Handler get_et_visible_course_nav_tools should be defined");

  const result = await handler(mockClient, {"context_codes[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/external_tools/visible_course_nav_tools");
  assert.deepStrictEqual(calledConfig.params, {"context_codes[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccet_visible_course_nav_tools calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = external_toolsModule.handlers.get_ccet_visible_course_nav_tools;
  assert.ok(handler, "Handler get_ccet_visible_course_nav_tools should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/external_tools/visible_course_nav_tools");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
