// Auto-generated tests for group_categories
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const group_categoriesModule = require("../tools/group_categories");

test("get_aa_group_categories calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_aa_group_categories;
  assert.ok(handler, "Handler get_aa_group_categories should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/group_categories");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_group_categories calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_cc_group_categories;
  assert.ok(handler, "Handler get_cc_group_categories should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "collaboration_state": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/group_categories");
  assert.deepStrictEqual(calledConfig.params, {"collaboration_state": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_group_categories_group_category_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_group_categories_group_category_id;
  assert.ok(handler, "Handler get_group_categories_group_category_id should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_group_categories calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.post_aa_group_categories;
  assert.ok(handler, "Handler post_aa_group_categories should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/group_categories");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_group_categories calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.post_cc_group_categories;
  assert.ok(handler, "Handler post_cc_group_categories should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "name": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/group_categories");
  assert.deepStrictEqual(calledConfig.data, {"name": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccgc_bulk_manage_differentiation_tag calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.post_ccgc_bulk_manage_differentiation_tag;
  assert.ok(handler, "Handler post_ccgc_bulk_manage_differentiation_tag should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "operations": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/group_categories/bulk_manage_differentiation_tag");
  assert.deepStrictEqual(calledConfig.data, {"operations": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccgc_import_tags calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.post_ccgc_import_tags;
  assert.ok(handler, "Handler post_ccgc_import_tags should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "attachment": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/group_categories/import_tags");
  assert.deepStrictEqual(calledConfig.data, {"attachment": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_gcg_import calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.post_gcg_import;
  assert.ok(handler, "Handler post_gcg_import should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id", "attachment": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id/import");
  assert.deepStrictEqual(calledConfig.data, {"attachment": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_group_categories_group_category_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.put_group_categories_group_category_id;
  assert.ok(handler, "Handler put_group_categories_group_category_id should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id", "name": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id");
  assert.deepStrictEqual(calledConfig.data, {"name": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_group_categories_group_category_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.delete_group_categories_group_category_id;
  assert.ok(handler, "Handler delete_group_categories_group_category_id should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gcg_groups calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_gcg_groups;
  assert.ok(handler, "Handler get_gcg_groups should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id/groups");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gcg_export calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_gcg_export;
  assert.ok(handler, "Handler get_gcg_export should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id/export");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccgc_export_tags calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_ccgc_export_tags;
  assert.ok(handler, "Handler get_ccgc_export_tags should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/group_categories/export_tags");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gcg_users calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.get_gcg_users;
  assert.ok(handler, "Handler get_gcg_users should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id", "search_term": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id/users");
  assert.deepStrictEqual(calledConfig.params, {"search_term": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_gcg_assign_unassigned_members calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = group_categoriesModule.handlers.post_gcg_assign_unassigned_members;
  assert.ok(handler, "Handler post_gcg_assign_unassigned_members should be defined");

  const result = await handler(mockClient, {"group_category_id": "test_group_category_id", "sync": true});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/group_categories/test_group_category_id/assign_unassigned_members");
  assert.deepStrictEqual(calledConfig.data, {"sync": true});
  assert.deepStrictEqual(result, { success: true });
});
