// Auto-generated tests for learning_object_dates
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const learning_object_datesModule = require("../tools/learning_object_dates");

test("get_ccmc_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.get_ccmc_date_details;
  assert.ok(handler, "Handler get_ccmc_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "context_module_id": "test_context_module_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_context_module_id/date_details");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.get_ccaa_date_details;
  assert.ok(handler, "Handler get_ccaa_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/date_details");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccqq_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.get_ccqq_date_details;
  assert.ok(handler, "Handler get_ccqq_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/date_details");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccdtd_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.get_ccdtd_date_details;
  assert.ok(handler, "Handler get_ccdtd_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "discussion_topic_id": "test_discussion_topic_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_discussion_topic_id/date_details");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccpu_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.get_ccpu_date_details;
  assert.ok(handler, "Handler get_ccpu_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/date_details");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccfa_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.get_ccfa_date_details;
  assert.ok(handler, "Handler get_ccfa_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "attachment_id": "test_attachment_id", "include[]": ["test_val"]});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/files/test_attachment_id/date_details");
  assert.deepStrictEqual(calledConfig.params, {"include[]": ["test_val"]});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaa_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.put_ccaa_date_details;
  assert.ok(handler, "Handler put_ccaa_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/date_details");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccqq_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.put_ccqq_date_details;
  assert.ok(handler, "Handler put_ccqq_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/date_details");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccdtd_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.put_ccdtd_date_details;
  assert.ok(handler, "Handler put_ccdtd_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "discussion_topic_id": "test_discussion_topic_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/discussion_topics/test_discussion_topic_id/date_details");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccpu_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.put_ccpu_date_details;
  assert.ok(handler, "Handler put_ccpu_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/date_details");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccfa_date_details calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = learning_object_datesModule.handlers.put_ccfa_date_details;
  assert.ok(handler, "Handler put_ccfa_date_details should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "attachment_id": "test_attachment_id", "due_at": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/files/test_attachment_id/date_details");
  assert.deepStrictEqual(calledConfig.data, {"due_at": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
