// Auto-generated tests for live_assessments
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const live_assessmentsModule = require("../tools/live_assessments");

test("post_cclaa_results calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = live_assessmentsModule.handlers.post_cclaa_results;
  assert.ok(handler, "Handler post_cclaa_results should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assessment_id": "test_assessment_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/live_assessments/test_assessment_id/results");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cclaa_results calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = live_assessmentsModule.handlers.get_cclaa_results;
  assert.ok(handler, "Handler get_cclaa_results should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assessment_id": "test_assessment_id", "user_id": 123});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/live_assessments/test_assessment_id/results");
  assert.deepStrictEqual(calledConfig.params, {"user_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_live_assessments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = live_assessmentsModule.handlers.post_cc_live_assessments;
  assert.ok(handler, "Handler post_cc_live_assessments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/live_assessments");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_live_assessments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = live_assessmentsModule.handlers.get_cc_live_assessments;
  assert.ok(handler, "Handler get_cc_live_assessments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/live_assessments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
