// Auto-generated tests for logins
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const loginsModule = require("../tools/logins");

test("get_aa_logins calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = loginsModule.handlers.get_aa_logins;
  assert.ok(handler, "Handler get_aa_logins should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/logins");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_logins calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = loginsModule.handlers.get_uu_logins;
  assert.ok(handler, "Handler get_uu_logins should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/logins");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_u_reset_password calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = loginsModule.handlers.post_u_reset_password;
  assert.ok(handler, "Handler post_u_reset_password should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/reset_password");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_logins calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = loginsModule.handlers.post_aa_logins;
  assert.ok(handler, "Handler post_aa_logins should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "user_id": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/logins");
  assert.deepStrictEqual(calledConfig.data, {"user[id]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_logins_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = loginsModule.handlers.put_aa_logins_id;
  assert.ok(handler, "Handler put_aa_logins_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "login_unique_id": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/logins/test_id");
  assert.deepStrictEqual(calledConfig.data, {"login[unique_id]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_uu_logins_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = loginsModule.handlers.delete_uu_logins_id;
  assert.ok(handler, "Handler delete_uu_logins_id should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/logins/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
