// Auto-generated tests for media_objects
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const media_objectsModule = require("../tools/media_objects");

test("get_mom_media_tracks calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_mom_media_tracks;
  assert.ok(handler, "Handler get_mom_media_tracks should be defined");

  const result = await handler(mockClient, {"media_object_id": "test_media_object_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/media_objects/test_media_object_id/media_tracks");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_maa_media_tracks calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_maa_media_tracks;
  assert.ok(handler, "Handler get_maa_media_tracks should be defined");

  const result = await handler(mockClient, {"attachment_id": "test_attachment_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/media_attachments/test_attachment_id/media_tracks");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_mom_media_tracks calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.put_mom_media_tracks;
  assert.ok(handler, "Handler put_mom_media_tracks should be defined");

  const result = await handler(mockClient, {"media_object_id": "test_media_object_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/media_objects/test_media_object_id/media_tracks");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_maa_media_tracks calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.put_maa_media_tracks;
  assert.ok(handler, "Handler put_maa_media_tracks should be defined");

  const result = await handler(mockClient, {"attachment_id": "test_attachment_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/media_attachments/test_attachment_id/media_tracks");
  assert.deepStrictEqual(calledConfig.data, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_media_objects calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_media_objects;
  assert.ok(handler, "Handler get_media_objects should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/media_objects");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_media_objects calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_cc_media_objects;
  assert.ok(handler, "Handler get_cc_media_objects should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/media_objects");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_media_objects calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_gg_media_objects;
  assert.ok(handler, "Handler get_gg_media_objects should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/media_objects");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_media_attachments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_media_attachments;
  assert.ok(handler, "Handler get_media_attachments should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/media_attachments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_media_attachments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_cc_media_attachments;
  assert.ok(handler, "Handler get_cc_media_attachments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/media_attachments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_media_attachments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.get_gg_media_attachments;
  assert.ok(handler, "Handler get_gg_media_attachments should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "sort": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/media_attachments");
  assert.deepStrictEqual(calledConfig.params, {"sort": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_media_objects_media_object_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.put_media_objects_media_object_id;
  assert.ok(handler, "Handler put_media_objects_media_object_id should be defined");

  const result = await handler(mockClient, {"media_object_id": "test_media_object_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/media_objects/test_media_object_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_media_attachments_attachment_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = media_objectsModule.handlers.put_media_attachments_attachment_id;
  assert.ok(handler, "Handler put_media_attachments_attachment_id should be defined");

  const result = await handler(mockClient, {"attachment_id": "test_attachment_id", "user_entered_title": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/media_attachments/test_attachment_id");
  assert.deepStrictEqual(calledConfig.data, {"user_entered_title": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
