// Auto-generated tests for moderated_grading
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const moderated_gradingModule = require("../tools/moderated_grading");

test("get_ccaa_moderated_students calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.get_ccaa_moderated_students;
  assert.ok(handler, "Handler get_ccaa_moderated_students should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/moderated_students");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccaa_moderated_students calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.post_ccaa_moderated_students;
  assert.ok(handler, "Handler post_ccaa_moderated_students should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "student_ids": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/moderated_students");
  assert.deepStrictEqual(calledConfig.data, {"student_ids[]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaapg_bulk_select calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.put_ccaapg_bulk_select;
  assert.ok(handler, "Handler put_ccaapg_bulk_select should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/provisional_grades/bulk_select");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaapg_status calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.get_ccaapg_status;
  assert.ok(handler, "Handler get_ccaapg_status should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "student_id": 123});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/provisional_grades/status");
  assert.deepStrictEqual(calledConfig.params, {"student_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaapgp_select calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.put_ccaapgp_select;
  assert.ok(handler, "Handler put_ccaapgp_select should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "provisional_grade_id": "test_provisional_grade_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/provisional_grades/test_provisional_grade_id/select");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccaapg_publish calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.post_ccaapg_publish;
  assert.ok(handler, "Handler post_ccaapg_publish should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/provisional_grades/publish");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaaapg_status calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = moderated_gradingModule.handlers.get_ccaaapg_status;
  assert.ok(handler, "Handler get_ccaaapg_status should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "anonymous_id": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/anonymous_provisional_grades/status");
  assert.deepStrictEqual(calledConfig.params, {"anonymous_id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});
