// Auto-generated tests for modules
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const modulesModule = require("../tools/modules");

test("get_cc_modules calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_cc_modules;
  assert.ok(handler, "Handler get_cc_modules should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_modules_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_cc_modules_id;
  assert.ok(handler, "Handler get_cc_modules_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_modules calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_cc_modules;
  assert.ok(handler, "Handler post_cc_modules should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_name": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules");
  assert.deepStrictEqual(calledConfig.data, {"module[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_modules_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_cc_modules_id;
  assert.ok(handler, "Handler put_cc_modules_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id", "module_name": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id");
  assert.deepStrictEqual(calledConfig.data, {"module[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_cc_modules_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.delete_cc_modules_id;
  assert.ok(handler, "Handler delete_cc_modules_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccmi_relock calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_ccmi_relock;
  assert.ok(handler, "Handler put_ccmi_relock should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_id/relock");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccmm_items calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_ccmm_items;
  assert.ok(handler, "Handler get_ccmm_items should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccmm_items_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_ccmm_items_id;
  assert.ok(handler, "Handler get_ccmm_items_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccmm_items calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_ccmm_items;
  assert.ok(handler, "Handler post_ccmm_items should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "module_item_title": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items");
  assert.deepStrictEqual(calledConfig.data, {"module_item[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccmm_items_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_ccmm_items_id;
  assert.ok(handler, "Handler put_ccmm_items_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id", "module_item_title": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id");
  assert.deepStrictEqual(calledConfig.data, {"module_item[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccmmii_select_mastery_path calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_ccmmii_select_mastery_path;
  assert.ok(handler, "Handler post_ccmmii_select_mastery_path should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id", "assignment_set_id": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id/select_mastery_path");
  assert.deepStrictEqual(calledConfig.data, {"assignment_set_id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccmm_items_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.delete_ccmm_items_id;
  assert.ok(handler, "Handler delete_ccmm_items_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccmmii_done calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_ccmmii_done;
  assert.ok(handler, "Handler put_ccmmii_done should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id/done");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_module_item_sequence calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_cc_module_item_sequence;
  assert.ok(handler, "Handler get_cc_module_item_sequence should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "asset_type": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/module_item_sequence");
  assert.deepStrictEqual(calledConfig.params, {"asset_type": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccmmii_mark_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.post_ccmmii_mark_read;
  assert.ok(handler, "Handler post_ccmmii_mark_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "module_id": "test_module_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_module_id/items/test_id/mark_read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccmc_assignment_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.get_ccmc_assignment_overrides;
  assert.ok(handler, "Handler get_ccmc_assignment_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "context_module_id": "test_context_module_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_context_module_id/assignment_overrides");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccmc_assignment_overrides calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = modulesModule.handlers.put_ccmc_assignment_overrides;
  assert.ok(handler, "Handler put_ccmc_assignment_overrides should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "context_module_id": "test_context_module_id", "overrides": ["test_val"]});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/modules/test_context_module_id/assignment_overrides");
  assert.deepStrictEqual(calledConfig.data, {"overrides[]": ["test_val"]});
  assert.deepStrictEqual(result, { success: true });
});
