// Auto-generated tests for new_quizzes
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const new_quizzesModule = require("../tools/new_quizzes");

test("get_qvcc_quizzes_assignment_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = new_quizzesModule.handlers.get_qvcc_quizzes_assignment_id;
  assert.ok(handler, "Handler get_qvcc_quizzes_assignment_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/quiz/v1/courses/test_course_id/quizzes/test_assignment_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_qvcc_quizzes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = new_quizzesModule.handlers.get_qvcc_quizzes;
  assert.ok(handler, "Handler get_qvcc_quizzes should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/quiz/v1/courses/test_course_id/quizzes");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_qvcc_quizzes calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = new_quizzesModule.handlers.post_qvcc_quizzes;
  assert.ok(handler, "Handler post_qvcc_quizzes should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/quiz/v1/courses/test_course_id/quizzes");
  assert.deepStrictEqual(calledConfig.data, {"quiz[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_qvcc_quizzes_assignment_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = new_quizzesModule.handlers.delete_qvcc_quizzes_assignment_id;
  assert.ok(handler, "Handler delete_qvcc_quizzes_assignment_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/quiz/v1/courses/test_course_id/quizzes/test_assignment_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
