// Auto-generated tests for originality_reports
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const originality_reportsModule = require("../tools/originality_reports");

test("post_aass_originality_report calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = originality_reportsModule.handlers.post_aass_originality_report;
  assert.ok(handler, "Handler post_aass_originality_report should be defined");

  const result = await handler(mockClient, {"assignment_id": "test_assignment_id", "submission_id": "test_submission_id", "originality_report_file_id": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/lti/assignments/test_assignment_id/submissions/test_submission_id/originality_report");
  assert.deepStrictEqual(calledConfig.data, {"originality_report[file_id]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aass_originality_report_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = originality_reportsModule.handlers.put_aass_originality_report_id;
  assert.ok(handler, "Handler put_aass_originality_report_id should be defined");

  const result = await handler(mockClient, {"assignment_id": "test_assignment_id", "submission_id": "test_submission_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/lti/assignments/test_assignment_id/submissions/test_submission_id/originality_report/test_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aaff_originality_report calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = originality_reportsModule.handlers.put_aaff_originality_report;
  assert.ok(handler, "Handler put_aaff_originality_report should be defined");

  const result = await handler(mockClient, {"assignment_id": "test_assignment_id", "file_id": "test_file_id", "originality_report_originality_score": 123});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/lti/assignments/test_assignment_id/files/test_file_id/originality_report");
  assert.deepStrictEqual(calledConfig.data, {"originality_report[originality_score]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aass_originality_report_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = originality_reportsModule.handlers.get_aass_originality_report_id;
  assert.ok(handler, "Handler get_aass_originality_report_id should be defined");

  const result = await handler(mockClient, {"assignment_id": "test_assignment_id", "submission_id": "test_submission_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/lti/assignments/test_assignment_id/submissions/test_submission_id/originality_report/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aaff_originality_report calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = originality_reportsModule.handlers.get_aaff_originality_report;
  assert.ok(handler, "Handler get_aaff_originality_report should be defined");

  const result = await handler(mockClient, {"assignment_id": "test_assignment_id", "file_id": "test_file_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/lti/assignments/test_assignment_id/files/test_file_id/originality_report");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
