// Auto-generated tests for pages
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const pagesModule = require("../tools/pages");

test("get_cc_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_cc_front_page;
  assert.ok(handler, "Handler get_cc_front_page should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/front_page");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_gg_front_page;
  assert.ok(handler, "Handler get_gg_front_page should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/front_page");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccpu_duplicate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_ccpu_duplicate;
  assert.ok(handler, "Handler post_ccpu_duplicate should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/duplicate");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_cc_front_page;
  assert.ok(handler, "Handler put_cc_front_page should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/front_page");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_gg_front_page calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_gg_front_page;
  assert.ok(handler, "Handler put_gg_front_page should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "wiki_page[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/front_page");
  assert.deepStrictEqual(calledConfig.data, {"wiki_page[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_cc_pages;
  assert.ok(handler, "Handler get_cc_pages should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_gg_pages;
  assert.ok(handler, "Handler get_gg_pages should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "sort": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages");
  assert.deepStrictEqual(calledConfig.params, {"sort": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_cc_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_cc_pages;
  assert.ok(handler, "Handler post_cc_pages should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_gg_pages calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_gg_pages;
  assert.ok(handler, "Handler post_gg_pages should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "wiki_page[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages");
  assert.deepStrictEqual(calledConfig.data, {"wiki_page[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_cc_pages_url_or_id;
  assert.ok(handler, "Handler get_cc_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_gg_pages_url_or_id;
  assert.ok(handler, "Handler get_gg_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_cc_pages_url_or_id;
  assert.ok(handler, "Handler put_cc_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_gg_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.put_gg_pages_url_or_id;
  assert.ok(handler, "Handler put_gg_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id", "wiki_page[title]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.data, {"wiki_page[title]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_cc_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.delete_cc_pages_url_or_id;
  assert.ok(handler, "Handler delete_cc_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_gg_pages_url_or_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.delete_gg_pages_url_or_id;
  assert.ok(handler, "Handler delete_gg_pages_url_or_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccpu_revisions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_ccpu_revisions;
  assert.ok(handler, "Handler get_ccpu_revisions should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggpu_revisions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_ggpu_revisions;
  assert.ok(handler, "Handler get_ggpu_revisions should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccpur_latest calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_ccpur_latest;
  assert.ok(handler, "Handler get_ccpur_latest should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions/latest");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggpur_latest calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_ggpur_latest;
  assert.ok(handler, "Handler get_ggpur_latest should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions/latest");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccpu_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_ccpu_revisions_revision_id;
  assert.ok(handler, "Handler get_ccpu_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ggpu_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.get_ggpu_revisions_revision_id;
  assert.ok(handler, "Handler get_ggpu_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id", "summary": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.params, {"summary": true});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccpu_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_ccpu_revisions_revision_id;
  assert.ok(handler, "Handler post_ccpu_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ggpu_revisions_revision_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = pagesModule.handlers.post_ggpu_revisions_revision_id;
  assert.ok(handler, "Handler post_ggpu_revisions_revision_id should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id", "url_or_id": "test_url_or_id", "revision_id": "test_revision_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/pages/test_url_or_id/revisions/test_revision_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});
