// Auto-generated tests for poll_sessions
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const poll_sessionsModule = require("../tools/poll_sessions");

test("get_pp_poll_sessions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.get_pp_poll_sessions;
  assert.ok(handler, "Handler get_pp_poll_sessions should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_pp_poll_sessions_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.get_pp_poll_sessions_id;
  assert.ok(handler, "Handler get_pp_poll_sessions_id should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_pp_poll_sessions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.post_pp_poll_sessions;
  assert.ok(handler, "Handler post_pp_poll_sessions should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id", "poll_sessions_course_id": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions");
  assert.deepStrictEqual(calledConfig.data, {"poll_sessions[][course_id]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_pp_poll_sessions_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.put_pp_poll_sessions_id;
  assert.ok(handler, "Handler put_pp_poll_sessions_id should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id", "id": "test_id", "poll_sessions_course_id": 123});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions/test_id");
  assert.deepStrictEqual(calledConfig.data, {"poll_sessions[][course_id]": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_pp_poll_sessions_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.delete_pp_poll_sessions_id;
  assert.ok(handler, "Handler delete_pp_poll_sessions_id should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_pppsi_open calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.get_pppsi_open;
  assert.ok(handler, "Handler get_pppsi_open should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions/test_id/open");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_pppsi_close calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.get_pppsi_close;
  assert.ok(handler, "Handler get_pppsi_close should be defined");

  const result = await handler(mockClient, {"poll_id": "test_poll_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/polls/test_poll_id/poll_sessions/test_id/close");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ps_opened calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.get_ps_opened;
  assert.ok(handler, "Handler get_ps_opened should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/poll_sessions/opened");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ps_closed calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = poll_sessionsModule.handlers.get_ps_closed;
  assert.ok(handler, "Handler get_ps_closed should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/poll_sessions/closed");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
