// Auto-generated tests for quiz_question_groups
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const quiz_question_groupsModule = require("../tools/quiz_question_groups");

test("get_ccqq_groups calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_question_groupsModule.handlers.get_ccqq_groups;
  assert.ok(handler, "Handler get_ccqq_groups should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/groups");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccqq_groups_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_question_groupsModule.handlers.get_ccqq_groups_id;
  assert.ok(handler, "Handler get_ccqq_groups_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/groups/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccqq_groups calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_question_groupsModule.handlers.post_ccqq_groups;
  assert.ok(handler, "Handler post_ccqq_groups should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id", "quiz_groups_name": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/groups");
  assert.deepStrictEqual(calledConfig.data, {"quiz_groups[][name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccqq_groups_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_question_groupsModule.handlers.put_ccqq_groups_id;
  assert.ok(handler, "Handler put_ccqq_groups_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id", "id": "test_id", "quiz_groups_name": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/groups/test_id");
  assert.deepStrictEqual(calledConfig.data, {"quiz_groups[][name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccqq_groups_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_question_groupsModule.handlers.delete_ccqq_groups_id;
  assert.ok(handler, "Handler delete_ccqq_groups_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id", "id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/groups/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccqqgi_reorder calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = quiz_question_groupsModule.handlers.post_ccqqgi_reorder;
  assert.ok(handler, "Handler post_ccqqgi_reorder should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "quiz_id": "test_quiz_id", "id": "test_id", "order_id": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/quizzes/test_quiz_id/groups/test_id/reorder");
  assert.deepStrictEqual(calledConfig.data, {"order[][id]": 123});
  assert.deepStrictEqual(result, { success: true });
});
