// Auto-generated tests for roles
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const rolesModule = require("../tools/roles");

test("get_aa_roles calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.get_aa_roles;
  assert.ok(handler, "Handler get_aa_roles should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "state": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles");
  assert.deepStrictEqual(calledConfig.params, {"state[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aa_roles_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.get_aa_roles_id;
  assert.ok(handler, "Handler get_aa_roles_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "role_id": 123});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles/test_id");
  assert.deepStrictEqual(calledConfig.params, {"role_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_roles calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.post_aa_roles;
  assert.ok(handler, "Handler post_aa_roles should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "label": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles");
  assert.deepStrictEqual(calledConfig.data, {"label": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_aa_roles_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.delete_aa_roles_id;
  assert.ok(handler, "Handler delete_aa_roles_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "role_id": 123});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles/test_id");
  assert.deepStrictEqual(calledConfig.params, {"role_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aari_activate calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.post_aari_activate;
  assert.ok(handler, "Handler post_aari_activate should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "role_id": 123});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles/test_id/activate");
  assert.deepStrictEqual(calledConfig.data, {"role_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_aa_roles_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.put_aa_roles_id;
  assert.ok(handler, "Handler put_aa_roles_id should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "id": "test_id", "label": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles/test_id");
  assert.deepStrictEqual(calledConfig.data, {"label": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_aar_permissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.get_aar_permissions;
  assert.ok(handler, "Handler get_aar_permissions should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "search_term": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/roles/permissions");
  assert.deepStrictEqual(calledConfig.params, {"search_term": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_pcp_help calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.get_pcp_help;
  assert.ok(handler, "Handler get_pcp_help should be defined");

  const result = await handler(mockClient, {"context_type": "test_context_type", "permission": "test_permission"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/permissions/test_context_type/test_permission/help");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_p_groups calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = rolesModule.handlers.get_p_groups;
  assert.ok(handler, "Handler get_p_groups should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/permissions/groups");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
