// Auto-generated tests for sis_integration
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const sis_integrationModule = require("../tools/sis_integration");

test("get_saa_assignments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = sis_integrationModule.handlers.get_saa_assignments;
  assert.ok(handler, "Handler get_saa_assignments should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/sis/accounts/test_account_id/assignments");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_scc_assignments calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = sis_integrationModule.handlers.get_scc_assignments;
  assert.ok(handler, "Handler get_scc_assignments should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "account_id": 123});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/sis/courses/test_course_id/assignments");
  assert.deepStrictEqual(calledConfig.params, {"account_id": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_scc_disable_post_to_sis calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = sis_integrationModule.handlers.put_scc_disable_post_to_sis;
  assert.ok(handler, "Handler put_scc_disable_post_to_sis should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "grading_period_id": 123});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/sis/courses/test_course_id/disable_post_to_sis");
  assert.deepStrictEqual(calledConfig.data, {"grading_period_id": 123});
  assert.deepStrictEqual(result, { success: true });
});
