// Auto-generated tests for submissions
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const submissionsModule = require("../tools/submissions");

test("post_ccaa_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ccaa_submissions;
  assert.ok(handler, "Handler post_ccaa_submissions should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ssaa_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ssaa_submissions;
  assert.ok(handler, "Handler post_ssaa_submissions should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "comment_text_comment": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions");
  assert.deepStrictEqual(calledConfig.data, {"comment[text_comment]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaa_submissions;
  assert.ok(handler, "Handler get_ccaa_submissions should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaa_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaa_submissions;
  assert.ok(handler, "Handler get_ssaa_submissions should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccs_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccs_submissions;
  assert.ok(handler, "Handler get_ccs_submissions should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/students/submissions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_sss_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_sss_submissions;
  assert.ok(handler, "Handler get_sss_submissions should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "student_ids": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/students/submissions");
  assert.deepStrictEqual(calledConfig.params, {"student_ids[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_submissions_user_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaa_submissions_user_id;
  assert.ok(handler, "Handler get_ccaa_submissions_user_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaa_submissions_user_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaa_submissions_user_id;
  assert.ok(handler, "Handler get_ssaa_submissions_user_id should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_anonymous_submissions_anonymous_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaa_anonymous_submissions_anonymous_id;
  assert.ok(handler, "Handler get_ccaa_anonymous_submissions_anonymous_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "anonymous_id": "test_anonymous_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/anonymous_submissions/test_anonymous_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaa_anonymous_submissions_anonymous_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaa_anonymous_submissions_anonymous_id;
  assert.ok(handler, "Handler get_ssaa_anonymous_submissions_anonymous_id should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "anonymous_id": "test_anonymous_id", "include": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/anonymous_submissions/test_anonymous_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccaasu_files calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ccaasu_files;
  assert.ok(handler, "Handler post_ccaasu_files should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/files");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ssaasu_files calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ssaasu_files;
  assert.ok(handler, "Handler post_ssaasu_files should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/files");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaa_submissions_user_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaa_submissions_user_id;
  assert.ok(handler, "Handler put_ccaa_submissions_user_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaa_submissions_user_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaa_submissions_user_id;
  assert.ok(handler, "Handler put_ssaa_submissions_user_id should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id", "comment_text_comment": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id");
  assert.deepStrictEqual(calledConfig.data, {"comment[text_comment]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaa_anonymous_submissions_anonymous_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaa_anonymous_submissions_anonymous_id;
  assert.ok(handler, "Handler put_ccaa_anonymous_submissions_anonymous_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "anonymous_id": "test_anonymous_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/anonymous_submissions/test_anonymous_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaa_anonymous_submissions_anonymous_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaa_anonymous_submissions_anonymous_id;
  assert.ok(handler, "Handler put_ssaa_anonymous_submissions_anonymous_id should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "anonymous_id": "test_anonymous_id", "comment_text_comment": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/anonymous_submissions/test_anonymous_id");
  assert.deepStrictEqual(calledConfig.data, {"comment[text_comment]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_gradeable_students calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaa_gradeable_students;
  assert.ok(handler, "Handler get_ccaa_gradeable_students should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "sort": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/gradeable_students");
  assert.deepStrictEqual(calledConfig.params, {"sort": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cca_gradeable_students calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_cca_gradeable_students;
  assert.ok(handler, "Handler get_cca_gradeable_students should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_ids": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/gradeable_students");
  assert.deepStrictEqual(calledConfig.params, {"assignment_ids[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccs_update_grades calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ccs_update_grades;
  assert.ok(handler, "Handler post_ccs_update_grades should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/submissions/update_grades");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ccaas_update_grades calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ccaas_update_grades;
  assert.ok(handler, "Handler post_ccaas_update_grades should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/update_grades");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_sss_update_grades calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_sss_update_grades;
  assert.ok(handler, "Handler post_sss_update_grades should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/submissions/update_grades");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ssaas_update_grades calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.post_ssaas_update_grades;
  assert.ok(handler, "Handler post_ssaas_update_grades should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "grade_data_student_id_posted_grade": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/update_grades");
  assert.deepStrictEqual(calledConfig.data, {"grade_data[<student_id>][posted_grade]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaasu_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaasu_read;
  assert.ok(handler, "Handler put_ccaasu_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaasu_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaasu_read;
  assert.ok(handler, "Handler put_ssaasu_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ccaasu_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.delete_ccaasu_read;
  assert.ok(handler, "Handler delete_ccaasu_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ssaasu_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.delete_ssaasu_read;
  assert.ok(handler, "Handler delete_ssaasu_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccs_bulk_mark_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccs_bulk_mark_read;
  assert.ok(handler, "Handler put_ccs_bulk_mark_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/submissions/bulk_mark_read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_sss_bulk_mark_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_sss_bulk_mark_read;
  assert.ok(handler, "Handler put_sss_bulk_mark_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "submissionIds": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/submissions/bulk_mark_read");
  assert.deepStrictEqual(calledConfig.data, {"submissionIds[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaasu_read_item calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaasu_read_item;
  assert.ok(handler, "Handler put_ccaasu_read_item should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id", "item": "test_item"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/read/test_item");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaasu_read_item calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaasu_read_item;
  assert.ok(handler, "Handler put_ssaasu_read_item should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id", "item": "test_item"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/read/test_item");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccsu_clear_unread calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccsu_clear_unread;
  assert.ok(handler, "Handler put_ccsu_clear_unread should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/submissions/test_user_id/clear_unread");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_sssu_clear_unread calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_sssu_clear_unread;
  assert.ok(handler, "Handler put_sssu_clear_unread should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/submissions/test_user_id/clear_unread");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaasurc_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaasurc_read;
  assert.ok(handler, "Handler get_ccaasurc_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/rubric_comments/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaasura_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaasura_read;
  assert.ok(handler, "Handler get_ccaasura_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/rubric_assessments/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaasurc_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaasurc_read;
  assert.ok(handler, "Handler get_ssaasurc_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/rubric_comments/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaasura_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaasura_read;
  assert.ok(handler, "Handler get_ssaasura_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/rubric_assessments/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaasurc_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaasurc_read;
  assert.ok(handler, "Handler put_ccaasurc_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/rubric_comments/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaasura_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaasura_read;
  assert.ok(handler, "Handler put_ccaasura_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/rubric_assessments/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaasurc_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaasurc_read;
  assert.ok(handler, "Handler put_ssaasurc_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/rubric_comments/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaasura_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaasura_read;
  assert.ok(handler, "Handler put_ssaasura_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/rubric_assessments/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaasuda_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaasuda_read;
  assert.ok(handler, "Handler get_ccaasuda_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/document_annotations/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaasuda_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaasuda_read;
  assert.ok(handler, "Handler get_ssaasuda_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/document_annotations/read");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccaasuda_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ccaasuda_read;
  assert.ok(handler, "Handler put_ccaasuda_read should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submissions/test_user_id/document_annotations/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ssaasuda_read calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.put_ssaasuda_read;
  assert.ok(handler, "Handler put_ssaasuda_read should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submissions/test_user_id/document_annotations/read");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ccaa_submission_summary calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ccaa_submission_summary;
  assert.ok(handler, "Handler get_ccaa_submission_summary should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "assignment_id": "test_assignment_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/assignments/test_assignment_id/submission_summary");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ssaa_submission_summary calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = submissionsModule.handlers.get_ssaa_submission_summary;
  assert.ok(handler, "Handler get_ssaa_submission_summary should be defined");

  const result = await handler(mockClient, {"section_id": "test_section_id", "assignment_id": "test_assignment_id", "grouped": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/sections/test_section_id/assignments/test_assignment_id/submission_summary");
  assert.deepStrictEqual(calledConfig.params, {"grouped": true});
  assert.deepStrictEqual(result, { success: true });
});
