// Auto-generated tests for tabs
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const tabsModule = require("../tools/tabs");

test("get_aa_tabs calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = tabsModule.handlers.get_aa_tabs;
  assert.ok(handler, "Handler get_aa_tabs should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/tabs");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_cc_tabs calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = tabsModule.handlers.get_cc_tabs;
  assert.ok(handler, "Handler get_cc_tabs should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/tabs");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_gg_tabs calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = tabsModule.handlers.get_gg_tabs;
  assert.ok(handler, "Handler get_gg_tabs should be defined");

  const result = await handler(mockClient, {"group_id": "test_group_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/groups/test_group_id/tabs");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_tabs calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = tabsModule.handlers.get_uu_tabs;
  assert.ok(handler, "Handler get_uu_tabs should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/tabs");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_cc_tabs_tab_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = tabsModule.handlers.put_cc_tabs_tab_id;
  assert.ok(handler, "Handler put_cc_tabs_tab_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "tab_id": "test_tab_id", "position": 123});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/tabs/test_tab_id");
  assert.deepStrictEqual(calledConfig.data, {"position": 123});
  assert.deepStrictEqual(result, { success: true });
});
