// Auto-generated tests for users
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const usersModule = require("../tools/users");

test("get_aa_users calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_aa_users;
  assert.ok(handler, "Handler get_aa_users should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "search_term": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/users");
  assert.deepStrictEqual(calledConfig.params, {"search_term": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_us_activity_stream calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_us_activity_stream;
  assert.ok(handler, "Handler get_us_activity_stream should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/activity_stream");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_u_activity_stream calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_u_activity_stream;
  assert.ok(handler, "Handler get_u_activity_stream should be defined");

  const result = await handler(mockClient, {"only_active_courses": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/activity_stream");
  assert.deepStrictEqual(calledConfig.params, {"only_active_courses": true});
  assert.deepStrictEqual(result, { success: true });
});

test("get_usas_summary calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_usas_summary;
  assert.ok(handler, "Handler get_usas_summary should be defined");

  const result = await handler(mockClient, {"only_active_courses": true});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/activity_stream/summary");
  assert.deepStrictEqual(calledConfig.params, {"only_active_courses": true});
  assert.deepStrictEqual(result, { success: true });
});

test("get_us_todo calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_us_todo;
  assert.ok(handler, "Handler get_us_todo should be defined");

  const result = await handler(mockClient, {"include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/todo");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_us_todo_item_count calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_us_todo_item_count;
  assert.ok(handler, "Handler get_us_todo_item_count should be defined");

  const result = await handler(mockClient, {"include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/todo_item_count");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_us_upcoming_events calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_us_upcoming_events;
  assert.ok(handler, "Handler get_us_upcoming_events should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/upcoming_events");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_missing_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uu_missing_submissions;
  assert.ok(handler, "Handler get_uu_missing_submissions should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "observed_user_id": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/missing_submissions");
  assert.deepStrictEqual(calledConfig.params, {"observed_user_id": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_us_activity_stream_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_us_activity_stream_id;
  assert.ok(handler, "Handler delete_us_activity_stream_id should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/activity_stream/test_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_us_activity_stream calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_us_activity_stream;
  assert.ok(handler, "Handler delete_us_activity_stream should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/activity_stream");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_uu_files calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_uu_files;
  assert.ok(handler, "Handler post_uu_files should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/files");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_users_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_users_id;
  assert.ok(handler, "Handler get_users_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_users calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_aa_users;
  assert.ok(handler, "Handler post_aa_users should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "user[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/users");
  assert.deepStrictEqual(calledConfig.data, {"user[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_aa_self_registration calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_aa_self_registration;
  assert.ok(handler, "Handler post_aa_self_registration should be defined");

  const result = await handler(mockClient, {"account_id": "test_account_id", "user[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/accounts/test_account_id/self_registration");
  assert.deepStrictEqual(calledConfig.data, {"user[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ui_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_ui_settings;
  assert.ok(handler, "Handler get_ui_settings should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/settings");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ui_settings calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_ui_settings;
  assert.ok(handler, "Handler put_ui_settings should be defined");

  const result = await handler(mockClient, {"id": "test_id", "manual_mark_as_read": true});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/settings");
  assert.deepStrictEqual(calledConfig.data, {"manual_mark_as_read": true});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ui_colors calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_ui_colors;
  assert.ok(handler, "Handler get_ui_colors should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/colors");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ui_colors_asset_string calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_ui_colors_asset_string;
  assert.ok(handler, "Handler get_ui_colors_asset_string should be defined");

  const result = await handler(mockClient, {"id": "test_id", "asset_string": "test_asset_string"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/colors/test_asset_string");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ui_colors_asset_string calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_ui_colors_asset_string;
  assert.ok(handler, "Handler put_ui_colors_asset_string should be defined");

  const result = await handler(mockClient, {"id": "test_id", "asset_string": "test_asset_string", "hexcode": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/colors/test_asset_string");
  assert.deepStrictEqual(calledConfig.data, {"hexcode": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ui_text_editor_preference calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_ui_text_editor_preference;
  assert.ok(handler, "Handler put_ui_text_editor_preference should be defined");

  const result = await handler(mockClient, {"id": "test_id", "text_editor_preference": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/text_editor_preference");
  assert.deepStrictEqual(calledConfig.data, {"text_editor_preference": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ui_files_ui_version_preference calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_ui_files_ui_version_preference;
  assert.ok(handler, "Handler put_ui_files_ui_version_preference should be defined");

  const result = await handler(mockClient, {"id": "test_id", "files_ui_version": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/files_ui_version_preference");
  assert.deepStrictEqual(calledConfig.data, {"files_ui_version": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ui_dashboard_positions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_ui_dashboard_positions;
  assert.ok(handler, "Handler get_ui_dashboard_positions should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/dashboard_positions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ui_dashboard_positions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_ui_dashboard_positions;
  assert.ok(handler, "Handler put_ui_dashboard_positions should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/dashboard_positions");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_users_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_users_id;
  assert.ok(handler, "Handler put_users_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "user[name]": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id");
  assert.deepStrictEqual(calledConfig.data, {"user[name]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ui_sessions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_ui_sessions;
  assert.ok(handler, "Handler delete_ui_sessions should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/sessions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_u_mobile_sessions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_u_mobile_sessions;
  assert.ok(handler, "Handler delete_u_mobile_sessions should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/mobile_sessions");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_ui_mobile_sessions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_ui_mobile_sessions;
  assert.ok(handler, "Handler delete_ui_mobile_sessions should be defined");

  const result = await handler(mockClient, {"id": "test_id", "skip_admins": true});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/mobile_sessions");
  assert.deepStrictEqual(calledConfig.params, {"skip_admins": true});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ui_merge_into_destination_user_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_ui_merge_into_destination_user_id;
  assert.ok(handler, "Handler put_ui_merge_into_destination_user_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "destination_user_id": "test_destination_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/merge_into/test_destination_user_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_uimiad_users_destination_user_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_uimiad_users_destination_user_id;
  assert.ok(handler, "Handler put_uimiad_users_destination_user_id should be defined");

  const result = await handler(mockClient, {"id": "test_id", "destination_account_id": "test_destination_account_id", "destination_user_id": "test_destination_user_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/merge_into/accounts/test_destination_account_id/users/test_destination_user_id");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_ui_split calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_ui_split;
  assert.ok(handler, "Handler post_ui_split should be defined");

  const result = await handler(mockClient, {"id": "test_id"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/split");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_us_pandata_events_token calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_us_pandata_events_token;
  assert.ok(handler, "Handler post_us_pandata_events_token should be defined");

  const result = await handler(mockClient, {"app_key": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/pandata_events_token");
  assert.deepStrictEqual(calledConfig.data, {"app_key": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_ui_graded_submissions calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_ui_graded_submissions;
  assert.ok(handler, "Handler get_ui_graded_submissions should be defined");

  const result = await handler(mockClient, {"id": "test_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_id/graded_submissions");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_profile calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uu_profile;
  assert.ok(handler, "Handler get_uu_profile should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "include[]": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/profile");
  assert.deepStrictEqual(calledConfig.params, {"include[]": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_avatars calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uu_avatars;
  assert.ok(handler, "Handler get_uu_avatars should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/avatars");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_page_views calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uu_page_views;
  assert.ok(handler, "Handler get_uu_page_views should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "start_time": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/page_views");
  assert.deepStrictEqual(calledConfig.params, {"start_time": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("post_uupv_query calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_uupv_query;
  assert.ok(handler, "Handler post_uupv_query should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "start_date": "test_val"});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/page_views/query");
  assert.deepStrictEqual(calledConfig.data, {"start_date": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uupv_query_query_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uupv_query_query_id;
  assert.ok(handler, "Handler get_uupv_query_query_id should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "query_id": "test_query_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/page_views/query/test_query_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uupvqq_results calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uupvqq_results;
  assert.ok(handler, "Handler get_uupvqq_results should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "query_id": "test_query_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/page_views/query/test_query_id/results");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("post_upv_query calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.post_upv_query;
  assert.ok(handler, "Handler post_upv_query should be defined");

  const result = await handler(mockClient, {"user_ids": ["test_val"]});

  assert.strictEqual(calledConfig.method, "post");
  assert.strictEqual(calledConfig.url, "/api/v1/users/page_views/query");
  assert.deepStrictEqual(calledConfig.data, {"user_ids": ["test_val"]});
  assert.deepStrictEqual(result, { success: true });
});

test("get_upv_query_query_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_upv_query_query_id;
  assert.ok(handler, "Handler get_upv_query_query_id should be defined");

  const result = await handler(mockClient, {"query_id": "test_query_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/page_views/query/test_query_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_upvqq_results calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_upvqq_results;
  assert.ok(handler, "Handler get_upvqq_results should be defined");

  const result = await handler(mockClient, {"query_id": "test_query_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/page_views/query/test_query_id/results");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_uu_custom_data_scope calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_uu_custom_data_scope;
  assert.ok(handler, "Handler put_uu_custom_data_scope should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "scope": "test_scope", "ns": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/custom_data(/test_scope)");
  assert.deepStrictEqual(calledConfig.data, {"ns": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_uu_custom_data_scope calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_uu_custom_data_scope;
  assert.ok(handler, "Handler get_uu_custom_data_scope should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "scope": "test_scope", "ns": "test_val"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/custom_data(/test_scope)");
  assert.deepStrictEqual(calledConfig.params, {"ns": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_uu_custom_data_scope calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_uu_custom_data_scope;
  assert.ok(handler, "Handler delete_uu_custom_data_scope should be defined");

  const result = await handler(mockClient, {"user_id": "test_user_id", "scope": "test_scope", "ns": "test_val"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/test_user_id/custom_data(/test_scope)");
  assert.deepStrictEqual(calledConfig.params, {"ns": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("get_us_course_nicknames calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_us_course_nicknames;
  assert.ok(handler, "Handler get_us_course_nicknames should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/course_nicknames");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("get_us_course_nicknames_course_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.get_us_course_nicknames_course_id;
  assert.ok(handler, "Handler get_us_course_nicknames_course_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "get");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/course_nicknames/test_course_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("put_us_course_nicknames_course_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.put_us_course_nicknames_course_id;
  assert.ok(handler, "Handler put_us_course_nicknames_course_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id", "nickname": "test_val"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/course_nicknames/test_course_id");
  assert.deepStrictEqual(calledConfig.data, {"nickname": "test_val"});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_us_course_nicknames_course_id calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_us_course_nicknames_course_id;
  assert.ok(handler, "Handler delete_us_course_nicknames_course_id should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/course_nicknames/test_course_id");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});

test("delete_us_course_nicknames calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = usersModule.handlers.delete_us_course_nicknames;
  assert.ok(handler, "Handler delete_us_course_nicknames should be defined");

  const result = await handler(mockClient, {});

  assert.strictEqual(calledConfig.method, "delete");
  assert.strictEqual(calledConfig.url, "/api/v1/users/self/course_nicknames");
  assert.deepStrictEqual(calledConfig.params, {});
  assert.deepStrictEqual(result, { success: true });
});
