// Auto-generated tests for what_if_grades
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const test = require("node:test");
const assert = require("node:assert");
const what_if_gradesModule = require("../tools/what_if_grades");

test("put_si_what_if_grades calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = what_if_gradesModule.handlers.put_si_what_if_grades;
  assert.ok(handler, "Handler put_si_what_if_grades should be defined");

  const result = await handler(mockClient, {"id": "test_id", "student_entered_score": 123});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/submissions/test_id/what_if_grades");
  assert.deepStrictEqual(calledConfig.data, {"student_entered_score": 123});
  assert.deepStrictEqual(result, { success: true });
});

test("put_ccwig_reset calls correct endpoint", async () => {
  let calledConfig = null;
  const mockClient = async (config) => {
    calledConfig = config;
    return { data: { success: true } };
  };

  const handler = what_if_gradesModule.handlers.put_ccwig_reset;
  assert.ok(handler, "Handler put_ccwig_reset should be defined");

  const result = await handler(mockClient, {"course_id": "test_course_id"});

  assert.strictEqual(calledConfig.method, "put");
  assert.strictEqual(calledConfig.url, "/api/v1/courses/test_course_id/what_if_grades/reset");
  assert.deepStrictEqual(calledConfig.data, {});
  assert.deepStrictEqual(result, { success: true });
});
