// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_ccaa_extensions",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/assignments/:assignment_id/extensions` \\Responses\\ * \\200 OK\\ if the request was successful * \\403 Forbidden\\ if you are not allowed to extend assignments for this course * \\400 Bad Request\\ if any of the extensions are invalid ```bash { \"assignment_extensions\": [{ \"user_id\": 3, \"extra_attempts\": 2 },{ \"user_id\": 2, \"extra_attempts\": 2 }] } ``` ```js { \"assignment_extensions\": [AssignmentExtension] } ``` *** This documentation is generated direc...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "assignment_id": {
          "type": "string",
          "description": "Path parameter: assignment_id"
        },
        "assignment_extensions_user_id": {
          "type": "number",
          "description": "The ID of the user we want to add assignment extensions for."
        },
        "assignment_extensions_extra_attempts": {
          "type": "number",
          "description": "<p>Number of times the student is allowed to re-take the assignment over the<br>limit.</p>"
        }
      },
      "required": [
        "course_id",
        "assignment_id",
        "assignment_extensions_user_id",
        "assignment_extensions_extra_attempts"
      ]
    }
  }
];

const handlers = {
  post_ccaa_extensions: async (client, args) => {
    const mappedArgs = { ...args };
    if ("assignment_extensions_user_id" in mappedArgs) {
      mappedArgs["assignment_extensions[][user_id]"] = mappedArgs["assignment_extensions_user_id"];
      delete mappedArgs["assignment_extensions_user_id"];
    }
    if ("assignment_extensions_extra_attempts" in mappedArgs) {
      mappedArgs["assignment_extensions[][extra_attempts]"] = mappedArgs["assignment_extensions_extra_attempts"];
      delete mappedArgs["assignment_extensions_extra_attempts"];
    }
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/assignments/:assignment_id/extensions", mappedArgs);
  }
};

module.exports = {
  definitions,
  handlers
};
