// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_cc_discussion_topics",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_gg_discussion_topics",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics` Returns the paginated list of discussion topics for this course or group. ```bash curl https:///api/v1/courses//discussion_topics \\ -H 'Authorization: Bearer ' ``` Returns a list of [DiscussionTopic](#discussiontopic) objects. [DiscussionTopicsController#create](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "include": {
          "type": "string",
          "description": "<p>If \"all\\_dates\" is passed, all dates associated with graded discussions'<br>assignments will be included.<br>if \"sections\" is passed, includes the course sections that are associated<br>with the topic, if the topic is specific to certain sections of the course.<br>If \"sections\\_user\\_count\" is passed, then:<br>(a) If sections were asked for <em>and</em> the topic is specific to certain<br>course sections, includes the number of users in each<br>section. (as part of the section json asked for above)<br>(b) Else, includes at the root level the total number of users in the<br>topic's context (group or course) that the topic applies to.<br>If \"overrides\" is passed, the overrides for the assignment will be included Allowed values: <code>all\\_dates</code>, <code>sections</code>, <code>sections\\_user\\_count</code>, <code>overrides</code></p>"
        },
        "order_by": {
          "type": "string",
          "description": "Determines the order of the discussion topic list. Defaults to \"position\". Allowed values: `position`, `recent_activity`, `title`"
        },
        "scope": {
          "type": "string",
          "description": "<p>Only return discussion topics in the given state(s). Defaults to including<br>all topics. Filtering is done after pagination, so pages<br>may be smaller than requested if topics are filtered.<br>Can pass multiple states as comma separated string. Allowed values: <code>locked</code>, <code>unlocked</code>, <code>pinned</code>, <code>unpinned</code></p>"
        },
        "only_announcements": {
          "type": "boolean",
          "description": "Return announcements instead of discussion topics. Defaults to false"
        },
        "filter_by": {
          "type": "string",
          "description": "The state of the discussion topic to return. Currently only supports unread state. Allowed values: `all`, `unread`"
        },
        "search_term": {
          "type": "string",
          "description": "The partial title of the discussion topics to match and return."
        },
        "exclude_context_module_locked_topics": {
          "type": "boolean",
          "description": "<p>For students, exclude topics that are locked by module progression.<br>Defaults to false.</p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "post_cc_discussion_topics",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "post_gg_discussion_topics",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics` Create an new discussion topic for the course or group. ```bash curl https:///api/v1/courses//discussion_topics \\ -F title='my topic' \\ -F message='initial message' \\ -F podcast_enabled=1 \\ -H 'Authorization: Bearer ' -F 'attachment=@' \\ ``` ```bash curl https:///api/v1/courses//discussion_topics \\ -F title='my assignment topic' \\ -F message='initial message' \\ -F assignment[points_possible]=15 \\ -H 'Authorization: Bearer ' ``` ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "title": {
          "type": "string",
          "description": "no description"
        },
        "message": {
          "type": "string",
          "description": "no description"
        },
        "discussion_type": {
          "type": "string",
          "description": "The type of discussion. Defaults to side\\_comment or not\\_threaded if not value is given. Accepted values are 'side\\_comment', 'not\\_threaded' for discussions that only allow one level of nested comments, and 'threaded' for fully threaded discussions. Allowed values: `side_comment`, `threaded`, `not_threaded`"
        },
        "published": {
          "type": "boolean",
          "description": "<p>Whether this topic is published (true) or draft state (false). Only<br>teachers and TAs have the ability to create draft state topics.</p>"
        },
        "delayed_post_at": {
          "type": "string",
          "description": "If a timestamp is given, the topic will not be published until that time."
        },
        "allow_rating": {
          "type": "boolean",
          "description": "Whether or not users can rate entries in this topic."
        },
        "lock_at": {
          "type": "string",
          "description": "<p>If a timestamp is given, the topic will be scheduled to lock at the<br>provided timestamp. If the timestamp is in the past, the topic will be<br>locked.</p>"
        },
        "podcast_enabled": {
          "type": "boolean",
          "description": "If true, the topic will have an associated podcast feed."
        },
        "podcast_has_student_posts": {
          "type": "boolean",
          "description": "<p>If true, the podcast will include posts from students as well. Implies<br>podcast\\_enabled.</p>"
        },
        "require_initial_post": {
          "type": "boolean",
          "description": "<p>If true then a user may not respond to other replies until that user has<br>made an initial reply. Defaults to false.</p>"
        },
        "assignment": {
          "type": "string",
          "description": "<p>To create an assignment discussion, pass the assignment parameters as a<br>sub-object. See the <a href=\"assignments.md#method.assignments_api.create\">Create an Assignment API</a><br>for the available parameters. The name parameter will be ignored, as it's<br>taken from the discussion title. If you want to make a discussion that was<br>an assignment NOT an assignment, pass set\\_assignment = false as part of<br>the assignment object</p>"
        },
        "is_announcement": {
          "type": "boolean",
          "description": "<p>If true, this topic is an announcement. It will appear in the<br>announcement's section rather than the discussions section. This requires<br>announcment-posting permissions.</p>"
        },
        "pinned": {
          "type": "boolean",
          "description": "If true, this topic will be listed in the \"Pinned Discussion\" section"
        },
        "position_after": {
          "type": "string",
          "description": "<p>By default, discussions are sorted chronologically by creation date, you<br>can pass the id of another topic to have this one show up after the other<br>when they are listed.</p>"
        },
        "group_category_id": {
          "type": "number",
          "description": "<p>If present, the topic will become a group discussion assigned<br>to the group.</p>"
        },
        "only_graders_can_rate": {
          "type": "boolean",
          "description": "If true, only graders will be allowed to rate entries."
        },
        "sort_order": {
          "type": "string",
          "description": "Default sort order of the discussion. Accepted values are \"asc\", \"desc\". Allowed values: `asc`, `desc`"
        },
        "sort_order_locked": {
          "type": "boolean",
          "description": "If true, users cannot choose their prefered sort order"
        },
        "expanded": {
          "type": "boolean",
          "description": "If true, thread will be expanded by default"
        },
        "expanded_locked": {
          "type": "boolean",
          "description": "If true, users cannot choose their prefered thread expansion setting"
        },
        "sort_by_rating": {
          "type": "boolean",
          "description": "(DEPRECATED) If true, entries will be sorted by rating."
        },
        "attachment": {
          "type": "string",
          "description": "<p>A multipart/form-data form-field-style attachment.<br>Attachments larger than 1 kilobyte are subject to quota restrictions.</p>"
        },
        "specific_sections": {
          "type": "string",
          "description": "<p>A comma-separated list of sections ids to which the discussion topic<br>should be made specific to. If it is not desired to make the discussion<br>topic specific to sections, then this parameter may be omitted or set to<br>\"all\". Can only be present only on announcements and only those that are<br>for a course (as opposed to a group).</p>"
        },
        "lock_comment": {
          "type": "boolean",
          "description": "If is\\_announcement and lock\\_comment are true, \u2018Allow Participants to Comment\u2019 setting is disabled."
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "put_cc_discussion_topics_topic_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_gg_discussion_topics_topic_id",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id` Update an existing discussion topic for the course or group. ```bash curl https:///api/v1/courses//discussion_topics/ \\ -F title='This will be positioned after Topic #1234' \\ -F position_after=1234 \\ -H 'Authorization: Bearer ' ``` [DiscussionTopicsController#destroy](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "title": {
          "type": "string",
          "description": "no description"
        },
        "message": {
          "type": "string",
          "description": "no description"
        },
        "discussion_type": {
          "type": "string",
          "description": "The type of discussion. Defaults to side\\_comment or not\\_threaded if not value is given. Accepted values are 'side\\_comment', 'not\\_threaded' for discussions that only allow one level of nested comments, and 'threaded' for fully threaded discussions. Allowed values: `side_comment`, `threaded`, `not_threaded`"
        },
        "published": {
          "type": "boolean",
          "description": "<p>Whether this topic is published (true) or draft state (false). Only<br>teachers and TAs have the ability to create draft state topics.</p>"
        },
        "delayed_post_at": {
          "type": "string",
          "description": "If a timestamp is given, the topic will not be published until that time."
        },
        "lock_at": {
          "type": "string",
          "description": "<p>If a timestamp is given, the topic will be scheduled to lock at the<br>provided timestamp. If the timestamp is in the past, the topic will be<br>locked.</p>"
        },
        "podcast_enabled": {
          "type": "boolean",
          "description": "If true, the topic will have an associated podcast feed."
        },
        "podcast_has_student_posts": {
          "type": "boolean",
          "description": "<p>If true, the podcast will include posts from students as well. Implies<br>podcast\\_enabled.</p>"
        },
        "require_initial_post": {
          "type": "boolean",
          "description": "<p>If true then a user may not respond to other replies until that user has<br>made an initial reply. Defaults to false.</p>"
        },
        "assignment": {
          "type": "string",
          "description": "<p>To create an assignment discussion, pass the assignment parameters as a<br>sub-object. See the <a href=\"assignments.md#method.assignments_api.create\">Create an Assignment API</a><br>for the available parameters. The name parameter will be ignored, as it's<br>taken from the discussion title. If you want to make a discussion that was<br>an assignment NOT an assignment, pass set\\_assignment = false as part of<br>the assignment object</p>"
        },
        "is_announcement": {
          "type": "boolean",
          "description": "<p>If true, this topic is an announcement. It will appear in the<br>announcement's section rather than the discussions section. This requires<br>announcment-posting permissions.</p>"
        },
        "pinned": {
          "type": "boolean",
          "description": "If true, this topic will be listed in the \"Pinned Discussion\" section"
        },
        "position_after": {
          "type": "string",
          "description": "<p>By default, discussions are sorted chronologically by creation date, you<br>can pass the id of another topic to have this one show up after the other<br>when they are listed.</p>"
        },
        "group_category_id": {
          "type": "number",
          "description": "<p>If present, the topic will become a group discussion assigned<br>to the group.</p>"
        },
        "allow_rating": {
          "type": "boolean",
          "description": "If true, users will be allowed to rate entries."
        },
        "only_graders_can_rate": {
          "type": "boolean",
          "description": "If true, only graders will be allowed to rate entries."
        },
        "sort_order": {
          "type": "string",
          "description": "Default sort order of the discussion. Accepted values are \"asc\", \"desc\". Allowed values: `asc`, `desc`"
        },
        "sort_order_locked": {
          "type": "boolean",
          "description": "If true, users cannot choose their prefered sort order"
        },
        "expanded": {
          "type": "boolean",
          "description": "If true, thread will be expanded by default"
        },
        "expanded_locked": {
          "type": "boolean",
          "description": "If true, users cannot choose their prefered thread expansion setting"
        },
        "sort_by_rating": {
          "type": "boolean",
          "description": "(DEPRECATED) If true, entries will be sorted by rating."
        },
        "specific_sections": {
          "type": "string",
          "description": "<p>A comma-separated list of sections ids to which the discussion topic<br>should be made specific too. If it is not desired to make the discussion<br>topic specific to sections, then this parameter may be omitted or set to<br>\"all\". Can only be present only on announcements and only those that are<br>for a course (as opposed to a group).</p>"
        },
        "lock_comment": {
          "type": "boolean",
          "description": "If is\\_announcement and lock\\_comment are true, \u2018Allow Participants to Comment\u2019 setting is disabled."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_cc_discussion_topics_topic_id",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/discussion_topics/:topic_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_gg_discussion_topics_topic_id",
    "description": "**Scope:** `url:DELETE|/api/v1/groups/:group_id/discussion_topics/:topic_id` Deletes the discussion topic. This will also delete the assignment, if it's an assignment discussion. ```bash curl -X DELETE https:///api/v1/courses//discussion_topics/ \\ -H 'Authorization: Bearer ' ``` [DiscussionTopicsController#reorder](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ccdt_reorder",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/reorder`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "post_ggdt_reorder",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/reorder` Puts the pinned discussion topics in the specified order. All pinned topics should be included. [DiscussionEntriesController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_entries_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "order": {
          "type": "number",
          "description": "<p>The ids of the pinned discussion topics in the desired order.<br>(For example, \"order=104,102,103\".)</p>"
        }
      },
      "required": [
        "group_id",
        "order"
      ]
    }
  },
  {
    "name": "put_ccdtt_entries_id",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "id"
      ]
    }
  },
  {
    "name": "put_ggdtt_entries_id",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:id` Update an existing discussion entry. The entry must have been created by the current user, or the current user must have admin rights to the discussion. If the edit is not allowed, a 401 will be returned. ```bash curl -X PUT 'https:///api/v1/courses//discussion_topics//entries/' \\ -F 'message=' \\ -H \"Authorization: Bearer \" ``` [DiscussionEntriesController#destroy](https://github.com/instructure/canvas-lms/b...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "message": {
          "type": "string",
          "description": "The updated body of the entry."
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_ccdtt_entries_id",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "id"
      ]
    }
  },
  {
    "name": "delete_ggdtt_entries_id",
    "description": "**Scope:** `url:DELETE|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:id` Delete a discussion entry. The entry must have been created by the current user, or the current user must have admin rights to the discussion. If the delete is not allowed, a 401 will be returned. The discussion will be marked deleted, and the user\\_id and message will be cleared out. ```bash curl -X DELETE 'https:///api/v1/courses//discussion_topics//entries/' \\ -H \"Authorization: Bearer \" ``` [Discussio...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "id"
      ]
    }
  },
  {
    "name": "get_cc_discussion_topics_topic_id",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:topic_id`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_gg_discussion_topics_topic_id",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics/:topic_id` Returns data on an individual discussion topic. See the List action for the response formatting. ```bash curl https:///api/v1/courses//discussion_topics/ \\ -H 'Authorization: Bearer ' ``` [DiscussionTopicsApiController#find\\_summary](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "include": {
          "type": "string",
          "description": "<p>If \"all\\_dates\" is passed, all dates associated with graded discussions'<br>assignments will be included.<br>if \"sections\" is passed, includes the course sections that are associated<br>with the topic, if the topic is specific to certain sections of the course.<br>If \"sections\\_user\\_count\" is passed, then:<br>(a) If sections were asked for <em>and</em> the topic is specific to certain<br>course sections, includes the number of users in each<br>section. (as part of the section json asked for above)<br>(b) Else, includes at the root level the total number of users in the<br>topic's context (group or course) that the topic applies to.<br>If \"overrides\" is passed, the overrides for the assignment will be included Allowed values: <code>all\\_dates</code>, <code>sections</code>, <code>sections\\_user\\_count</code>, <code>overrides</code></p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_ccdtt_summaries",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_ggdtt_summaries",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries` Returns: (1) last userInput (what current user had keyed in to produce the last discussion summary), (2) last discussion summary generated by the current user for current discussion topic, based on userInput, (3) and some usage information. ```bash curl https:///api/v1/courses//discussion_topics//summaries \\ -H 'Authorization: Bearer ' ``` ```js { \"id\": 1, \"userInput\": \"Give me a brief summary of the discussio...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ccdtt_summaries",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ggdtt_summaries",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries` Generates a summary for a discussion topic. Returns the summary text and usage information. ```bash curl https:///api/v1/courses//discussion_topics//summaries \\ -X POST \\ -H 'Authorization: Bearer ' ``` ```js { \"id\": 1, \"text\": \"This is a summary of the discussion topic.\", \"usage\": { \"currentCount\": 1, \"limit\": 5 } } ``` [DiscussionTopicsApiController#disable\\_summary](https://github.com/instructure/canvas-lm...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "userInput": {
          "type": "string",
          "description": "Areas or topics for the summary to focus on."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ccdtts_disable",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries/disable`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ggdtts_disable",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries/disable` Deprecated, to remove after VICE-5047 gets merged Disables the summary for a discussion topic. ```bash curl -X PUT https:///api/v1/courses//discussion_topics//disable_summary \\ ``` ```js { \"success\": true } ``` [DiscussionTopicsApiController#summary\\_feedback](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ccdttss_feedback",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries/:summary_id/feedback`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "summary_id": {
          "type": "string",
          "description": "Path parameter: summary_id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "summary_id"
      ]
    }
  },
  {
    "name": "post_ggdttss_feedback",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries/:summary_id/feedback` Persists feedback on a discussion topic summary. ```bash curl -X POST https:///api/v1/courses//discussion_topics//summaries//feedback \\ -F '_action=like' \\ -H \"Authorization: Bearer ``` ```js { \"liked\": true, \"disliked\": false } ``` [DiscussionTopicsApiController#view](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "summary_id": {
          "type": "string",
          "description": "Path parameter: summary_id"
        },
        "action": {
          "type": "string",
          "description": "<p>Required<br>The action to take on the summary. Possible values are:<br>- \"seen\": Marks the summary as seen. This action saves the feedback if it's not already persisted.<br>- \"like\": Marks the summary as liked.<br>- \"dislike\": Marks the summary as disliked.<br>- \"add\\_comment\": Adds a written comment to a disliked summary. Requires the \"comment\" parameter.<br>- \"reset\\_like\": Resets the like status of the summary.<br>- \"regenerate\": Regenerates the summary feedback.<br>- \"disable\\_summary\": Disables the summary feedback.<br>Any other value will result in an error response.</p>"
        },
        "comment": {
          "type": "string",
          "description": "<p>Optional<br>A written explanation for the dislike. Only used with the \"add\\_comment\" action. Maximum 1024 characters.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "summary_id"
      ]
    }
  },
  {
    "name": "get_ccdtt_view",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:topic_id/view`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_ggdtt_view",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics/:topic_id/view` Return a cached structure of the discussion topic, containing all entries, their authors, and their message bodies. May require (depending on the topic) that the user has posted in the topic. If it is required, and the user has not posted, will respond with a 403 Forbidden status and the body 'require\\_initial\\_post'. In some rare situations, this cached structure may not be available yet. In that case, the server ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ccdtt_entries",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ggdtt_entries",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries` Create a new entry in a discussion topic. Returns a json representation of the created entry (see documentation for 'entries' method) on success. ```bash curl 'https:///api/v1/courses//discussion_topics//entries.json' \\ -F 'message=' \\ -F 'attachment=@' \\ -H \"Authorization: Bearer \" ``` [DiscussionTopicsApiController#duplicate](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_top...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "message": {
          "type": "string",
          "description": "The body of the entry."
        },
        "attachment": {
          "type": "string",
          "description": "<p>a multipart/form-data form-field-style<br>attachment. Attachments larger than 1 kilobyte are subject to quota<br>restrictions.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ccdtt_duplicate",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/:topic_id/duplicate`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ggdtt_duplicate",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/:topic_id/duplicate` Duplicate a discussion topic according to context (Course/Group) ```bash curl -X POST -H 'Authorization: Bearer ' \\ https:///api/v1/courses/123/discussion_topics/123/duplicate curl -X POST -H 'Authorization: Bearer ' \\ https:///api/v1/group/456/discussion_topics/456/duplicate ``` Returns a [DiscussionTopic](#discussiontopic) object. [DiscussionTopicsApiController#entries](https://github.com/instructure/canvas...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_ccdtt_entries",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_ggdtt_entries",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries` Retrieve the (paginated) top-level entries in a discussion topic. May require (depending on the topic) that the user has posted in the topic. If it is required, and the user has not posted, will respond with a 403 Forbidden status and the body 'require\\_initial\\_post'. Will include the 10 most recent replies, if any, for each entry returned. If the topic is a root topic with children corresponding to groups of a...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "post_ccdttee_replies",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/replies`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "post_ggdttee_replies",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/replies` Add a reply to an entry in a discussion topic. Returns a json representation of the created reply (see documentation for 'replies' method) on success. May require (depending on the topic) that the user has posted in the topic. If it is required, and the user has not posted, will respond with a 403 Forbidden status and the body 'require\\_initial\\_post'. ```bash curl 'https:///api/v1/courses//di...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        },
        "message": {
          "type": "string",
          "description": "The body of the entry."
        },
        "attachment": {
          "type": "string",
          "description": "<p>a multipart/form-data form-field-style<br>attachment. Attachments larger than 1 kilobyte are subject to quota<br>restrictions.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "get_ccdttee_replies",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/replies`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "get_ggdttee_replies",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/replies` Retrieve the (paginated) replies to a top-level entry in a discussion topic. May require (depending on the topic) that the user has posted in the topic. If it is required, and the user has not posted, will respond with a 403 Forbidden status and the body 'require\\_initial\\_post'. Ordering of returned entries is newest-first by creation timestamp. * id The unique identifier for the reply. * user...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "get_ccdtt_entry_list",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/discussion_topics/:topic_id/entry_list`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "get_ggdtt_entry_list",
    "description": "**Scope:** `url:GET|/api/v1/groups/:group_id/discussion_topics/:topic_id/entry_list` Retrieve a paginated list of discussion entries, given a list of ids. May require (depending on the topic) that the user has posted in the topic. If it is required, and the user has not posted, will respond with a 403 Forbidden status and the body 'require\\_initial\\_post'. * id The unique identifier for the reply. * user\\_id The unique identifier for the author of the reply. * user\\_name The author's display ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "ids": {
          "type": "string",
          "description": "<p>A list of entry ids to retrieve. Entries will be returned in id order,<br>smallest id first.</p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ccdtt_read",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id/read`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ggdtt_read",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id/read` Mark the initial text of the discussion topic as read. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//read.json' \\ -X PUT \\ -H \"Authorization: Bearer \" \\ -H \"Content-Length: 0\" ``` [DiscussionTopicsApiController#mark\\_all\\_topic\\_read](https://github.com/instructure/canvas-lms/blob/master/app/controllers/...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ccdt_read_all",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/read_all`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "put_ggdt_read_all",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/read_all` Mark the initial text of all the discussion topics as read in the context. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics/read_all' \\ -X POST \\ -H \"Authorization: Bearer \" \\ -H \"Content-Length: 0\" ``` [DiscussionTopicsApiController#mark\\_topic\\_unread](https://github.com/instructure/canvas-lms/blob/master/app/co...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        }
      },
      "required": [
        "group_id"
      ]
    }
  },
  {
    "name": "delete_ccdtt_read",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/discussion_topics/:topic_id/read`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_ggdtt_read",
    "description": "**Scope:** `url:DELETE|/api/v1/groups/:group_id/discussion_topics/:topic_id/read` Mark the initial text of the discussion topic as unread. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//read.json' \\ -X DELETE \\ -H \"Authorization: Bearer \" ``` [DiscussionTopicsApiController#mark\\_all\\_read](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_api_co...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ccdtt_read_all",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id/read_all`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ggdtt_read_all",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id/read_all` Mark the discussion topic and all its entries as read. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//read_all.json' \\ -X PUT \\ -H \"Authorization: Bearer \" \\ -H \"Content-Length: 0\" ``` [DiscussionTopicsApiController#mark\\_all\\_unread](https://github.com/instructure/canvas-lms/blob/master/app/controlle...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "forced_read_state": {
          "type": "boolean",
          "description": "<p>A boolean value to set all of the entries' forced\\_read\\_state. No change<br>is made if this argument is not specified.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_ccdtt_read_all",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/discussion_topics/:topic_id/read_all`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_ggdtt_read_all",
    "description": "**Scope:** `url:DELETE|/api/v1/groups/:group_id/discussion_topics/:topic_id/read_all` Mark the discussion topic and all its entries as unread. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//read_all.json' \\ -X DELETE \\ -H \"Authorization: Bearer \" ``` [DiscussionTopicsApiController#mark\\_entry\\_read](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_top...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "forced_read_state": {
          "type": "boolean",
          "description": "<p>A boolean value to set all of the entries' forced\\_read\\_state. No change is<br>made if this argument is not specified.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ccdttee_read",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/read`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "put_ggdttee_read",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/read` Mark a discussion entry as read. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//entries//read.json' \\ -X PUT \\ -H \"Authorization: Bearer \"\\ -H \"Content-Length: 0\" ``` [DiscussionTopicsApiController#mark\\_entry\\_unread](https://github.com/instructure/canvas-lms/blob/master/app/controllers...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        },
        "forced_read_state": {
          "type": "boolean",
          "description": "<p>A boolean value to set the entry's forced\\_read\\_state. No change is made if<br>this argument is not specified.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "delete_ccdttee_read",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/read`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "delete_ggdttee_read",
    "description": "**Scope:** `url:DELETE|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/read` Mark a discussion entry as unread. No request fields are necessary. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//entries//read.json' \\ -X DELETE \\ -H \"Authorization: Bearer \" ``` [DiscussionTopicsApiController#rate\\_entry](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_api_c...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        },
        "forced_read_state": {
          "type": "boolean",
          "description": "<p>A boolean value to set the entry's forced\\_read\\_state. No change is made if<br>this argument is not specified.</p>"
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "post_ccdttee_rating",
    "description": "**Scope:** `url:POST|/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/rating`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        }
      },
      "required": [
        "course_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "post_ggdttee_rating",
    "description": "**Scope:** `url:POST|/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/rating` Rate a discussion entry. On success, the response will be 204 No Content with an empty body. ```bash curl 'https:///api/v1/courses//discussion_topics//entries//rating.json' \\ -X POST \\ -H \"Authorization: Bearer \" ``` [DiscussionTopicsApiController#subscribe\\_topic](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics_api_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        },
        "entry_id": {
          "type": "string",
          "description": "Path parameter: entry_id"
        },
        "rating": {
          "type": "number",
          "description": "A rating to set on this entry. Only 0 and 1 are accepted."
        }
      },
      "required": [
        "group_id",
        "topic_id",
        "entry_id"
      ]
    }
  },
  {
    "name": "put_ccdtt_subscribed",
    "description": "**Scope:** `url:PUT|/api/v1/courses/:course_id/discussion_topics/:topic_id/subscribed`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "put_ggdtt_subscribed",
    "description": "**Scope:** `url:PUT|/api/v1/groups/:group_id/discussion_topics/:topic_id/subscribed` Subscribe to a topic to receive notifications about new entries On success, the response will be 204 No Content with an empty body ```bash curl 'https:///api/v1/courses//discussion_topics//subscribed.json' \\ -X PUT \\ -H \"Authorization: Bearer \" \\ -H \"Content-Length: 0\" ``` [DiscussionTopicsApiController#unsubscribe\\_topic](https://github.com/instructure/canvas-lms/blob/master/app/controllers/discussion_topics...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_ccdtt_subscribed",
    "description": "**Scope:** `url:DELETE|/api/v1/courses/:course_id/discussion_topics/:topic_id/subscribed`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "course_id",
        "topic_id"
      ]
    }
  },
  {
    "name": "delete_ggdtt_subscribed",
    "description": "**Scope:** `url:DELETE|/api/v1/groups/:group_id/discussion_topics/:topic_id/subscribed` Unsubscribe from a topic to stop receiving notifications about new entries On success, the response will be 204 No Content with an empty body ```bash curl 'https:///api/v1/courses//discussion_topics//subscribed.json' \\ -X DELETE \\ -H \"Authorization: Bearer \" ``` *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "group_id": {
          "type": "string",
          "description": "Path parameter: group_id"
        },
        "topic_id": {
          "type": "string",
          "description": "Path parameter: topic_id"
        }
      },
      "required": [
        "group_id",
        "topic_id"
      ]
    }
  }
];

const handlers = {
  get_cc_discussion_topics: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics", args);
  },
  get_gg_discussion_topics: async (client, args) => {
    const mappedArgs = { ...args };
    if ("include" in mappedArgs) {
      mappedArgs["include[]"] = mappedArgs["include"];
      delete mappedArgs["include"];
    }
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics", mappedArgs);
  },
  post_cc_discussion_topics: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics", args);
  },
  post_gg_discussion_topics: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics", args);
  },
  put_cc_discussion_topics_topic_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id", args);
  },
  put_gg_discussion_topics_topic_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id", args);
  },
  delete_cc_discussion_topics_topic_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/discussion_topics/:topic_id", args);
  },
  delete_gg_discussion_topics_topic_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/groups/:group_id/discussion_topics/:topic_id", args);
  },
  post_ccdt_reorder: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/reorder", args);
  },
  post_ggdt_reorder: async (client, args) => {
    const mappedArgs = { ...args };
    if ("order" in mappedArgs) {
      mappedArgs["order[]"] = mappedArgs["order"];
      delete mappedArgs["order"];
    }
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/reorder", mappedArgs);
  },
  put_ccdtt_entries_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:id", args);
  },
  put_ggdtt_entries_id: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:id", args);
  },
  delete_ccdtt_entries_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:id", args);
  },
  delete_ggdtt_entries_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:id", args);
  },
  get_cc_discussion_topics_topic_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:topic_id", args);
  },
  get_gg_discussion_topics_topic_id: async (client, args) => {
    const mappedArgs = { ...args };
    if ("include" in mappedArgs) {
      mappedArgs["include[]"] = mappedArgs["include"];
      delete mappedArgs["include"];
    }
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics/:topic_id", mappedArgs);
  },
  get_ccdtt_summaries: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries", args);
  },
  get_ggdtt_summaries: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries", args);
  },
  post_ccdtt_summaries: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries", args);
  },
  post_ggdtt_summaries: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries", args);
  },
  put_ccdtts_disable: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries/disable", args);
  },
  put_ggdtts_disable: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries/disable", args);
  },
  post_ccdttss_feedback: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/:topic_id/summaries/:summary_id/feedback", args);
  },
  post_ggdttss_feedback: async (client, args) => {
    const mappedArgs = { ...args };
    if ("action" in mappedArgs) {
      mappedArgs["_action"] = mappedArgs["action"];
      delete mappedArgs["action"];
    }
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/:topic_id/summaries/:summary_id/feedback", mappedArgs);
  },
  get_ccdtt_view: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:topic_id/view", args);
  },
  get_ggdtt_view: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics/:topic_id/view", args);
  },
  post_ccdtt_entries: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries", args);
  },
  post_ggdtt_entries: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries", args);
  },
  post_ccdtt_duplicate: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/:topic_id/duplicate", args);
  },
  post_ggdtt_duplicate: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/:topic_id/duplicate", args);
  },
  get_ccdtt_entries: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries", args);
  },
  get_ggdtt_entries: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries", args);
  },
  post_ccdttee_replies: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/replies", args);
  },
  post_ggdttee_replies: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/replies", args);
  },
  get_ccdttee_replies: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/replies", args);
  },
  get_ggdttee_replies: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/replies", args);
  },
  get_ccdtt_entry_list: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entry_list", args);
  },
  get_ggdtt_entry_list: async (client, args) => {
    const mappedArgs = { ...args };
    if ("ids" in mappedArgs) {
      mappedArgs["ids[]"] = mappedArgs["ids"];
      delete mappedArgs["ids"];
    }
    return genericHandler(client, "GET", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entry_list", mappedArgs);
  },
  put_ccdtt_read: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id/read", args);
  },
  put_ggdtt_read: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id/read", args);
  },
  put_ccdt_read_all: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/read_all", args);
  },
  put_ggdt_read_all: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/read_all", args);
  },
  delete_ccdtt_read: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/discussion_topics/:topic_id/read", args);
  },
  delete_ggdtt_read: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/groups/:group_id/discussion_topics/:topic_id/read", args);
  },
  put_ccdtt_read_all: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id/read_all", args);
  },
  put_ggdtt_read_all: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id/read_all", args);
  },
  delete_ccdtt_read_all: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/discussion_topics/:topic_id/read_all", args);
  },
  delete_ggdtt_read_all: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/groups/:group_id/discussion_topics/:topic_id/read_all", args);
  },
  put_ccdttee_read: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/read", args);
  },
  put_ggdttee_read: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/read", args);
  },
  delete_ccdttee_read: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/read", args);
  },
  delete_ggdttee_read: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/read", args);
  },
  post_ccdttee_rating: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/courses/:course_id/discussion_topics/:topic_id/entries/:entry_id/rating", args);
  },
  post_ggdttee_rating: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/groups/:group_id/discussion_topics/:topic_id/entries/:entry_id/rating", args);
  },
  put_ccdtt_subscribed: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/courses/:course_id/discussion_topics/:topic_id/subscribed", args);
  },
  put_ggdtt_subscribed: async (client, args) => {
    return genericHandler(client, "PUT", "/api/v1/groups/:group_id/discussion_topics/:topic_id/subscribed", args);
  },
  delete_ccdtt_subscribed: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/courses/:course_id/discussion_topics/:topic_id/subscribed", args);
  },
  delete_ggdtt_subscribed: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/groups/:group_id/discussion_topics/:topic_id/subscribed", args);
  }
};

module.exports = {
  definitions,
  handlers
};
