// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "post_error_reports",
    "description": "**Scope:** `url:POST|/api/v1/error_reports` Create a new error report documenting an experienced problem Performs the same action as when a user uses the \"help -> report a problem\" dialog. ```bash curl 'https:///api/v1/error_reports' \\ -X POST \\ -F 'error[subject]=\"things are broken\"' \\ -F 'error[url]=http:///courses/1' \\ -F 'error[description]=\"All my thoughts on what I saw\"' \\ -H 'Authorization: Bearer ' ``` *** This documentation is generated directly from the Canvas LMS source code, avail...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "error_subject": {
          "type": "string",
          "description": "The summary of the problem"
        },
        "error_url": {
          "type": "string",
          "description": "URL from which the report was issued"
        },
        "error_email": {
          "type": "string",
          "description": "Email address for the reporting user"
        },
        "error_comments": {
          "type": "string",
          "description": "The long version of the story from the user one what they experienced"
        },
        "error_http_env": {
          "type": "string",
          "description": "<p>A collection of metadata about the users' environment. If not provided,<br>canvas will collect it based on information found in the request.<br>(Doesn't have to be HTTPENV info, could be anything JSON object that can be<br>serialized as a hash, a mobile app might include relevant metadata for<br>itself)</p>"
        }
      },
      "required": [
        "error_subject"
      ]
    }
  }
];

const handlers = {
  post_error_reports: async (client, args) => {
    const mappedArgs = { ...args };
    if ("error_subject" in mappedArgs) {
      mappedArgs["error[subject]"] = mappedArgs["error_subject"];
      delete mappedArgs["error_subject"];
    }
    if ("error_url" in mappedArgs) {
      mappedArgs["error[url]"] = mappedArgs["error_url"];
      delete mappedArgs["error_url"];
    }
    if ("error_email" in mappedArgs) {
      mappedArgs["error[email]"] = mappedArgs["error_email"];
      delete mappedArgs["error_email"];
    }
    if ("error_comments" in mappedArgs) {
      mappedArgs["error[comments]"] = mappedArgs["error_comments"];
      delete mappedArgs["error_comments"];
    }
    if ("error_http_env" in mappedArgs) {
      mappedArgs["error[http_env]"] = mappedArgs["error_http_env"];
      delete mappedArgs["error_http_env"];
    }
    return genericHandler(client, "POST", "/api/v1/error_reports", mappedArgs);
  }
};

module.exports = {
  definitions,
  handlers
};
