// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_ccla_launch_definitions",
    "description": "**Scope:** `url:GET|/api/v1/courses/:course_id/lti_apps/launch_definitions`",
    "inputSchema": {
      "type": "object",
      "properties": {
        "course_id": {
          "type": "string",
          "description": "Path parameter: course_id"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "course_id"
      ]
    }
  },
  {
    "name": "get_aala_launch_definitions",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/lti_apps/launch_definitions` List all tools available in this context for the given placements, in the form of Launch Definitions. Used primarily by the Canvas frontend. API users should consider using the External Tools API instead. This endpoint is cached for 10 minutes! *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is publ...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "placements_Array": {
          "type": "string",
          "description": "The placements to return launch definitions for. If not provided, an empty list will be returned."
        },
        "only_visible_Boolean": {
          "type": "string",
          "description": "If true, only return launch definitions that are visible to the current user. Defaults to true."
        },
        "include_context_name_Boolean": {
          "type": "string",
          "description": "If true, includes the deployment context name (account or course) of the tool definition in the response. This helps distinguish between tools with identical names deployed at different levels of the context hierarchy. Defaults to false."
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  }
];

const handlers = {
  get_ccla_launch_definitions: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/courses/:course_id/lti_apps/launch_definitions", args);
  },
  get_aala_launch_definitions: async (client, args) => {
    const mappedArgs = { ...args };
    if ("placements_Array" in mappedArgs) {
      mappedArgs["placements[Array]"] = mappedArgs["placements_Array"];
      delete mappedArgs["placements_Array"];
    }
    if ("only_visible_Boolean" in mappedArgs) {
      mappedArgs["only_visible[Boolean]"] = mappedArgs["only_visible_Boolean"];
      delete mappedArgs["only_visible_Boolean"];
    }
    if ("include_context_name_Boolean" in mappedArgs) {
      mappedArgs["include_context_name[Boolean]"] = mappedArgs["include_context_name_Boolean"];
      delete mappedArgs["include_context_name_Boolean"];
    }
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/lti_apps/launch_definitions", mappedArgs);
  }
};

module.exports = {
  definitions,
  handlers
};
