// Auto-generated MCP Tools for Canvas LMS API
// Generated by generate_tools.py - DO NOT EDIT MANUALLY

const { genericHandler } = require("./helper");

const definitions = [
  {
    "name": "get_aa_roles",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/roles` A paginated list of the roles available to an account. Returns a list of [Role](#role) objects. [RoleOverridesController#show](https://github.com/instructure/canvas-lms/blob/master/app/controllers/role_overrides_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "The id of the account to retrieve roles for."
        },
        "state": {
          "type": "string",
          "description": "<p>Filter by role state. If this argument is omitted, only 'active' roles are<br>returned. Allowed values: <code>active</code>, <code>inactive</code></p>"
        },
        "show_inherited": {
          "type": "boolean",
          "description": "<p>If this argument is true, all roles inherited from parent accounts will<br>be included.</p>"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_aa_roles_id",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/roles/:id` Retrieve information about a single role Returns a [Role](#role) object. [RoleOverridesController#add\\_role](https://github.com/instructure/canvas-lms/blob/master/app/controllers/role_overrides_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "The id of the account containing the role"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "role_id": {
          "type": "number",
          "description": "The unique identifier for the role"
        },
        "role": {
          "type": "string",
          "description": "The name for the role"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id",
        "id",
        "role_id"
      ]
    }
  },
  {
    "name": "post_aa_roles",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/roles` Create a new course-level or account-level role. ```bash curl 'https:///api/v1/accounts//roles.json' \\ -H \"Authorization: Bearer \" \\ -F 'label=New Role' \\ -F 'permissions[read_course_content][explicit]=1' \\ -F 'permissions[read_course_content][enabled]=1' \\ -F 'permissions[read_course_list][locked]=1' \\ -F 'permissions[read_question_banks][explicit]=1' \\ -F 'permissions[read_question_banks][enabled]=0' \\ -F 'permissions[read_question_ba...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "label": {
          "type": "string",
          "description": "Label for the role."
        },
        "role": {
          "type": "string",
          "description": "Deprecated alias for label."
        },
        "base_role_type": {
          "type": "string",
          "description": "<p>Specifies the role type that will be used as a base<br>for the permissions granted to this role.<br>Defaults to 'AccountMembership' if absent Allowed values: <code>AccountMembership</code>, <code>StudentEnrollment</code>, <code>TeacherEnrollment</code>, <code>TaEnrollment</code>, <code>ObserverEnrollment</code>, <code>DesignerEnrollment</code></p>"
        },
        "permissions_X_explicit": {
          "type": "boolean",
          "description": "no description"
        },
        "permissions_X_enabled": {
          "type": "boolean",
          "description": "<p>If explicit is 1 and enabled is 1, permission \\<X> will be explicitly<br>granted to this role. If explicit is 1 and enabled has any other value<br>(typically 0), permission \\<X> will be explicitly denied to this role. If<br>explicit is any other value (typically 0) or absent, or if enabled is<br>absent, the value for permission \\<X> will be inherited from upstream.<br>Ignored if permission \\<X> is locked upstream (in an ancestor account).<br>May occur multiple times with unique values for \\<X>. Recognized<br>permission names for \\<X> can be found on the<br><a href=\"../permissions/file.permissions.md\">Permissions list page</a>.<br>Some of these permissions are applicable only for roles on the site admin<br>account, on a root account, or for course-level roles with a particular base role type;<br>if a specified permission is inapplicable, it will be ignored.<br>Additional permissions may exist based on installed plugins.<br>A comprehensive list of all permissions are available:<br>Course Permissions PDF: <http://bit.ly/cnvs-course-permissions><br>Account Permissions PDF: <http://bit.ly/cnvs-acct-permissions></p>"
        },
        "permissions_X_locked": {
          "type": "boolean",
          "description": "<p>If the value is 1, permission \\<X> will be locked downstream (new roles in<br>subaccounts cannot override the setting). For any other value, permission<br>\\<X> is left unlocked. Ignored if permission \\<X> is already locked<br>upstream. May occur multiple times with unique values for \\<X>.</p>"
        },
        "permissions_X_applies_to_self": {
          "type": "boolean",
          "description": "<p>If the value is 1, permission \\<X> applies to the account this role is in.<br>The default value is 1. Must be true if applies\\_to\\_descendants is false.<br>This value is only returned if enabled is true.</p>"
        },
        "permissions_X_applies_to_descendants": {
          "type": "boolean",
          "description": "<p>If the value is 1, permission \\<X> cascades down to sub accounts of the<br>account this role is in. The default value is 1. Must be true if<br>applies\\_to\\_self is false.This value is only returned if enabled is true.</p>"
        }
      },
      "required": [
        "account_id",
        "label"
      ]
    }
  },
  {
    "name": "delete_aa_roles_id",
    "description": "**Scope:** `url:DELETE|/api/v1/accounts/:account_id/roles/:id` Deactivates a custom role. This hides it in the user interface and prevents it from being assigned to new users. Existing users assigned to the role will continue to function with the same permissions they had previously. Built-in roles cannot be deactivated. Returns a [Role](#role) object. [RoleOverridesController#activate\\_role](https://github.com/instructure/canvas-lms/blob/master/app/controllers/role_overrides_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "role_id": {
          "type": "number",
          "description": "The unique identifier for the role"
        },
        "role": {
          "type": "string",
          "description": "The name for the role"
        }
      },
      "required": [
        "account_id",
        "id",
        "role_id"
      ]
    }
  },
  {
    "name": "post_aari_activate",
    "description": "**Scope:** `url:POST|/api/v1/accounts/:account_id/roles/:id/activate` Re-activates an inactive role (allowing it to be assigned to new users) Returns a [Role](#role) object. [RoleOverridesController#update](https://github.com/instructure/canvas-lms/blob/master/app/controllers/role_overrides_controller.rb)",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "role_id": {
          "type": "number",
          "description": "The unique identifier for the role"
        },
        "role": {
          "type": "string",
          "description": "The name for the role"
        }
      },
      "required": [
        "account_id",
        "id",
        "role_id"
      ]
    }
  },
  {
    "name": "put_aa_roles_id",
    "description": "**Scope:** `url:PUT|/api/v1/accounts/:account_id/roles/:id` Update permissions for an existing role. Recognized roles are: * TeacherEnrollment * StudentEnrollment * TaEnrollment * ObserverEnrollment * DesignerEnrollment * AccountAdmin * Any previously created custom role ```bash curl https:///api/v1/accounts/:account_id/roles/2 \\ -X PUT \\ -H 'Authorization: Bearer ' \\ -F 'label=New Role Name' \\ -F 'permissions[manage_groups][explicit]=1' \\ -F 'permissions[manage_groups][enabled]=1' \\ -F 'perm...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "id": {
          "type": "string",
          "description": "Path parameter: id"
        },
        "label": {
          "type": "string",
          "description": "The label for the role. Can only change the label of a custom role that belongs directly to the account."
        },
        "permissions_X_explicit": {
          "type": "boolean",
          "description": "no description"
        },
        "permissions_X_enabled": {
          "type": "boolean",
          "description": "<p>These arguments are described in the documentation for the<br><a href=\"#method.role_overrides.add_role\">add\\_role method</a>.<br>The list of available permissions can be found on the<br><a href=\"../permissions/file.permissions.md\">Permissions list page</a>.</p>"
        },
        "permissions_X_applies_to_self": {
          "type": "boolean",
          "description": "<p>If the value is 1, permission \\<X> applies to the account this role is in.<br>The default value is 1. Must be true if applies\\_to\\_descendants is false.<br>This value is only returned if enabled is true.</p>"
        },
        "permissions_X_applies_to_descendants": {
          "type": "boolean",
          "description": "<p>If the value is 1, permission \\<X> cascades down to sub accounts of the<br>account this role is in. The default value is 1. Must be true if<br>applies\\_to\\_self is false.This value is only returned if enabled is true.</p>"
        }
      },
      "required": [
        "account_id",
        "id"
      ]
    }
  },
  {
    "name": "get_aar_permissions",
    "description": "**Scope:** `url:GET|/api/v1/accounts/:account_id/roles/permissions` List all permissions that can be granted to roles in the given account. This returns largely the same information documented on the [Permissions list page](../permissions/file.permissions.md), with a few caveats: * Permission labels and group labels returned by this API are localized (the same text visible in the web UI). * This API includes permissions added by plugins. * This API excludes permissions that are disabled in or...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "account_id": {
          "type": "string",
          "description": "Path parameter: account_id"
        },
        "search_term": {
          "type": "string",
          "description": "If provided, return only permissions whose key, label, group, or group\\_label match the search string."
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "account_id"
      ]
    }
  },
  {
    "name": "get_pcp_help",
    "description": "**Scope:** `url:GET|/api/v1/permissions/:context_type/:permission/help` these actions access only static (but localized) information about permissions, but require a logged-in user to mitigate possible abuse Retrieve information about what Canvas permissions do and considerations for their use. ```bash curl -H 'Authorization: Bearer ' \\ https:///api/v1/permissions/account/view_user_logins/help ``` Returns a [PermissionHelpText](#permissionhelptext) object. [PermissionsHelpController#groups](h...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "context_type": {
          "type": "string",
          "description": "Path parameter: context_type"
        },
        "permission": {
          "type": "string",
          "description": "Path parameter: permission"
        },
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      },
      "required": [
        "context_type",
        "permission"
      ]
    }
  },
  {
    "name": "get_p_groups",
    "description": "**Scope:** `url:GET|/api/v1/permissions/groups` Retrieve information about groups of granular permissions The return value is a dictionary of permission group keys to objects containing +label+ and +subtitle+ keys. *** This documentation is generated directly from the Canvas LMS source code, available [on Github](https://github.com/instructure/canvas-lms). --- This documentation is published with GitBook. GitBook is the documentation platform designed so that both humans and AI agents can rea...",
    "inputSchema": {
      "type": "object",
      "properties": {
        "fetch_all_pages": {
          "type": "boolean",
          "description": "Optional: Set to true to automatically paginate and return all pages of results. Default is false."
        }
      }
    }
  }
];

const handlers = {
  get_aa_roles: async (client, args) => {
    const mappedArgs = { ...args };
    if ("state" in mappedArgs) {
      mappedArgs["state[]"] = mappedArgs["state"];
      delete mappedArgs["state"];
    }
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/roles", mappedArgs);
  },
  get_aa_roles_id: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/roles/:id", args);
  },
  post_aa_roles: async (client, args) => {
    const mappedArgs = { ...args };
    if ("permissions_X_explicit" in mappedArgs) {
      mappedArgs["permissions[<X>][explicit]"] = mappedArgs["permissions_X_explicit"];
      delete mappedArgs["permissions_X_explicit"];
    }
    if ("permissions_X_enabled" in mappedArgs) {
      mappedArgs["permissions[<X>][enabled]"] = mappedArgs["permissions_X_enabled"];
      delete mappedArgs["permissions_X_enabled"];
    }
    if ("permissions_X_locked" in mappedArgs) {
      mappedArgs["permissions[<X>][locked]"] = mappedArgs["permissions_X_locked"];
      delete mappedArgs["permissions_X_locked"];
    }
    if ("permissions_X_applies_to_self" in mappedArgs) {
      mappedArgs["permissions[<X>][applies_to_self]"] = mappedArgs["permissions_X_applies_to_self"];
      delete mappedArgs["permissions_X_applies_to_self"];
    }
    if ("permissions_X_applies_to_descendants" in mappedArgs) {
      mappedArgs["permissions[<X>][applies_to_descendants]"] = mappedArgs["permissions_X_applies_to_descendants"];
      delete mappedArgs["permissions_X_applies_to_descendants"];
    }
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/roles", mappedArgs);
  },
  delete_aa_roles_id: async (client, args) => {
    return genericHandler(client, "DELETE", "/api/v1/accounts/:account_id/roles/:id", args);
  },
  post_aari_activate: async (client, args) => {
    return genericHandler(client, "POST", "/api/v1/accounts/:account_id/roles/:id/activate", args);
  },
  put_aa_roles_id: async (client, args) => {
    const mappedArgs = { ...args };
    if ("permissions_X_explicit" in mappedArgs) {
      mappedArgs["permissions[<X>][explicit]"] = mappedArgs["permissions_X_explicit"];
      delete mappedArgs["permissions_X_explicit"];
    }
    if ("permissions_X_enabled" in mappedArgs) {
      mappedArgs["permissions[<X>][enabled]"] = mappedArgs["permissions_X_enabled"];
      delete mappedArgs["permissions_X_enabled"];
    }
    if ("permissions_X_applies_to_self" in mappedArgs) {
      mappedArgs["permissions[<X>][applies_to_self]"] = mappedArgs["permissions_X_applies_to_self"];
      delete mappedArgs["permissions_X_applies_to_self"];
    }
    if ("permissions_X_applies_to_descendants" in mappedArgs) {
      mappedArgs["permissions[<X>][applies_to_descendants]"] = mappedArgs["permissions_X_applies_to_descendants"];
      delete mappedArgs["permissions_X_applies_to_descendants"];
    }
    return genericHandler(client, "PUT", "/api/v1/accounts/:account_id/roles/:id", mappedArgs);
  },
  get_aar_permissions: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/accounts/:account_id/roles/permissions", args);
  },
  get_pcp_help: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/permissions/:context_type/:permission/help", args);
  },
  get_p_groups: async (client, args) => {
    return genericHandler(client, "GET", "/api/v1/permissions/groups", args);
  }
};

module.exports = {
  definitions,
  handlers
};
